/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 60010
Source Host           : localhost:3306
Source Database       : charmword

Target Server Type    : MYSQL
Target Server Version : 60010
File Encoding         : 65001

Date: 2014-09-04 11:07:20
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for test
-- ----------------------------
DROP TABLE IF EXISTS `test`;
CREATE TABLE `test` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `tea` varchar(255) DEFAULT NULL,
  `eat` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of test
-- ----------------------------
INSERT INTO `test` VALUES ('1', '33', 'qq');
INSERT INTO `test` VALUES ('2', '2', null);

-- ----------------------------
-- Table structure for word
-- ----------------------------
DROP TABLE IF EXISTS `word`;
CREATE TABLE `word` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `wordID` int(11) NOT NULL DEFAULT '0',
  `word` varchar(255) DEFAULT NULL,
  `phonetics` varchar(255) DEFAULT NULL,
  `voicePath` varchar(255) DEFAULT NULL,
  `explain` varchar(255) DEFAULT NULL,
  `wordType` varchar(255) DEFAULT NULL,
  `example` varchar(255) DEFAULT NULL,
  `exampleExplain` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=2746 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- ----------------------------
-- Records of word
-- ----------------------------
INSERT INTO `word` VALUES ('2061', '1', 'alter', '[\'ɔ:ltə]', null, 'v.改变，改动，变更', null, null, null);
INSERT INTO `word` VALUES ('2062', '2', 'burst', '[bə:st]', null, 'vi.,n.突然发生，爆裂', null, null, null);
INSERT INTO `word` VALUES ('2063', '3', 'dispose', '[dis\'pəuz]', null, 'vi.除掉；处置；解决；处理(of)', null, null, null);
INSERT INTO `word` VALUES ('2064', '4', 'blast', '[\'baiəu,blæst]', null, 'n.爆炸；气流 vi.炸，炸掉', null, null, null);
INSERT INTO `word` VALUES ('2065', '5', 'consume', '[kən\'sju:m]', null, 'v.消耗，耗尽', null, null, null);
INSERT INTO `word` VALUES ('2066', '6', 'split', '[split]', null, 'v.劈开；割裂；分裂 a.裂开的', null, null, null);
INSERT INTO `word` VALUES ('2067', '7', 'spit', '[spit]', null, 'v.吐（唾液等）；唾弃', null, null, null);
INSERT INTO `word` VALUES ('2068', '8', 'spill', '[spil]', null, 'v.溢出，溅出，倒出', null, null, null);
INSERT INTO `word` VALUES ('2069', '9', 'slip', '[slip]', null, 'v.滑动，滑落；忽略', null, null, null);
INSERT INTO `word` VALUES ('2070', '10', 'slide', '[slaid]', null, 'v.滑动，滑落 n.滑动；滑面；幻灯片', null, null, null);
INSERT INTO `word` VALUES ('2071', '11', 'bacteria', '[bæk\'tiəriə]', null, 'n.细菌', null, null, null);
INSERT INTO `word` VALUES ('2072', '12', 'breed', '[bri:d]', null, 'n.种，品种 v.繁殖，产仔', null, null, null);
INSERT INTO `word` VALUES ('2073', '13', 'budget', '[\'bʌdʒit]', null, 'n.预算 v.编预算，作安排', null, null, null);
INSERT INTO `word` VALUES ('2074', '14', 'candidate', '[\'kændideit, -dət]', null, 'n.候选人', null, null, null);
INSERT INTO `word` VALUES ('2075', '15', 'campus', '[\'kæmpəs]', null, 'n.校园', null, null, null);
INSERT INTO `word` VALUES ('2076', '16', 'liberal', '[\'libərəl]', null, 'a.慷慨的；丰富的；自由的', null, null, null);
INSERT INTO `word` VALUES ('2077', '17', 'transform', '[træns\'fɔ:m, trænz-, trɑ:n-]', null, 'v.转变，变革；变换', null, null, null);
INSERT INTO `word` VALUES ('2078', '18', 'transmit', '[trænz\'mit, træns-, trɑ:n-]', null, 'v.传播，播送；传递', null, null, null);
INSERT INTO `word` VALUES ('2079', '19', 'transplant', '[træns\'plɑ:nt, trænz-, trɑ:n-, -\'plænt]', null, 'v.移植', null, null, null);
INSERT INTO `word` VALUES ('2080', '20', 'transport', '[træn\'spɔːt; trɑːn-]', null, 'vt.运输，运送 n.运输，运输工具', null, null, null);
INSERT INTO `word` VALUES ('2081', '21', 'shift', '[ʃift]', null, 'v.转移；转动；转变', null, null, null);
INSERT INTO `word` VALUES ('2082', '22', 'vary', '[\'vεəri]', null, 'v.变化，改变；使多样化', null, null, null);
INSERT INTO `word` VALUES ('2083', '23', 'vanish', '[\'væniʃ]', null, 'vi.消灭，不见', null, null, null);
INSERT INTO `word` VALUES ('2084', '24', 'swallow', '[\'swɔləu]', null, 'v.吞下，咽下 n.燕子', null, null, null);
INSERT INTO `word` VALUES ('2085', '25', 'suspicion', '[sə\'spiʃən]', null, 'n.怀疑，疑心', null, null, null);
INSERT INTO `word` VALUES ('2086', '26', 'suspicious', '[sə\'spiʃəs]', null, 'a.怀疑的，可疑的', null, null, null);
INSERT INTO `word` VALUES ('2087', '27', 'mild', '[maild]', null, 'a.温暖的，暖和的；温柔的，味淡的', null, null, null);
INSERT INTO `word` VALUES ('2088', '28', 'tender', '[\'tendə]', null, 'a.温柔的；脆弱的', null, null, null);
INSERT INTO `word` VALUES ('2089', '29', 'nuisance', '[\'nju:səns]', null, 'n.损害，妨害，讨厌（的人或事物）', null, null, null);
INSERT INTO `word` VALUES ('2090', '30', 'insignificant', '[ɪnsɪg\'nɪfɪk(ə)nt]', null, 'a.无意义的，无足轻重的；无价值的', null, null, null);
INSERT INTO `word` VALUES ('2091', '31', 'accelerate', '[ək\'seləreit]', null, 'vt.加速，促进', null, null, null);
INSERT INTO `word` VALUES ('2092', '32', 'absolute', '[\'æbsəlju:t, ,æbsə\'lju:t]', null, 'a.绝对的，无条件的；完全的', null, null, null);
INSERT INTO `word` VALUES ('2093', '33', 'boundary', '[\'baundəri]', null, 'n.分界线，边界', null, null, null);
INSERT INTO `word` VALUES ('2094', '34', 'brake', '[breik]', null, 'n.刹车，制动器 v.刹住（车）', null, null, null);
INSERT INTO `word` VALUES ('2095', '35', 'catalog', '[\'kætəlɔɡ]', null, 'n.目录（册） v.编目', null, null, null);
INSERT INTO `word` VALUES ('2096', '36', 'vague', '[veiɡ]', null, 'a.模糊的，不明确的', null, null, null);
INSERT INTO `word` VALUES ('2097', '37', 'vain', '[vein]', null, 'n.徒劳，白费', null, null, null);
INSERT INTO `word` VALUES ('2098', '38', 'extinct', '[ik\'stiŋkt]', null, 'a.绝灭的，熄灭的', null, null, null);
INSERT INTO `word` VALUES ('2099', '39', 'extraordinary', '[ik\'strɔ:dənəri, ,ekstrə\'ɔ:di-]', null, 'a.不平常的，特别的，非凡的', null, null, null);
INSERT INTO `word` VALUES ('2100', '40', 'extreme', '[ik\'stri:m]', null, 'a.极度的，极端的 n.极端，过分', null, null, null);
INSERT INTO `word` VALUES ('2101', '41', 'agent', '[\'eidʒənt]', null, 'n.代理人，代理商；动因，原因', null, null, null);
INSERT INTO `word` VALUES ('2102', '42', 'alcohol', '[\'ælkəhɔl]', null, 'n.含酒精的饮料，酒精', null, null, null);
INSERT INTO `word` VALUES ('2103', '43', 'appeal', '[ə\'pi:l]', null, 'n./vi.呼吁，恳求', null, null, null);
INSERT INTO `word` VALUES ('2104', '44', 'appreciate', '[ə\'pri:ʃieit]', null, 'vt.重视，赏识，欣赏', null, null, null);
INSERT INTO `word` VALUES ('2105', '45', 'approve', '[ə\'pru:v]', null, 'v.赞成，同意，批准', null, null, null);
INSERT INTO `word` VALUES ('2106', '46', 'stimulate', '[\'stimjuleit]', null, 'vt.刺激，激励', null, null, null);
INSERT INTO `word` VALUES ('2107', '47', 'acquire', '[ə\'kwaiə]', null, 'vt.取得，获得；学到', null, null, null);
INSERT INTO `word` VALUES ('2108', '48', 'accomplish', '[ə\'kʌmpliʃ, ə\'kɔm-]', null, 'vt .完成，到达；实行', null, null, null);
INSERT INTO `word` VALUES ('2109', '49', 'network', '[\'netwə:k]', null, 'n.网状物；广播网，电视网；网络', null, null, null);
INSERT INTO `word` VALUES ('2110', '50', 'tide', '[taid]', null, 'n.潮汐；潮流', null, null, null);
INSERT INTO `word` VALUES ('2111', '51', 'tidy', '[\'taidi]', null, 'a.整洁的，整齐的', null, null, null);
INSERT INTO `word` VALUES ('2112', '52', 'trace', '[treis]', null, 'vt.追踪，找到 n.痕迹，踪迹', null, null, null);
INSERT INTO `word` VALUES ('2113', '53', 'torture', '[\'tɔ:tʃə]', null, 'n./vt.拷打，折磨', null, null, null);
INSERT INTO `word` VALUES ('2114', '54', 'wander', '[\'wɔndə]', null, 'vi.漫游，闲逛', null, null, null);
INSERT INTO `word` VALUES ('2115', '55', 'wax', '[wæks]', null, 'n.蜡', null, null, null);
INSERT INTO `word` VALUES ('2116', '56', 'weave', '[wi:v]', null, 'v.织，编', null, null, null);
INSERT INTO `word` VALUES ('2117', '57', 'preserve', '[pri\'zə:v]', null, 'v.保护，保存，保持，维持', null, null, null);
INSERT INTO `word` VALUES ('2118', '61', 'abuse', '[ə\'bju:z, ə\'bju:s]', null, 'v.滥用，虐待；谩骂', null, null, null);
INSERT INTO `word` VALUES ('2119', '62', 'academic', '[,ækə\'demik]', null, 'a.学术的；高等院校的；研究院的', null, null, null);
INSERT INTO `word` VALUES ('2120', '63', 'academy', '[ə\'kædəmi]', null, 'n.（高等）专科院校；学会', null, null, null);
INSERT INTO `word` VALUES ('2121', '64', 'battery', '[\'bætəri]', null, 'n.电池（组）', null, null, null);
INSERT INTO `word` VALUES ('2122', '65', 'barrier', '[\'bæriə]', null, 'n.障碍；棚栏', null, null, null);
INSERT INTO `word` VALUES ('2123', '66', 'cargo', '[\'kɑ:ɡəu]', null, 'n.（船、飞机等装载的）货物', null, null, null);
INSERT INTO `word` VALUES ('2124', '67', 'career', '[kə\'riə]', null, 'n.生涯，职业', null, null, null);
INSERT INTO `word` VALUES ('2125', '68', 'vessel', '[\'vesəl]', null, 'n.船舶；容器，器皿；血管', null, null, null);
INSERT INTO `word` VALUES ('2126', '69', 'vertical', '[\'və:tikəl]', null, 'a.垂直的', null, null, null);
INSERT INTO `word` VALUES ('2127', '70', 'oblige', '[ə\'blaidʒ]', null, 'v.迫使，责成；使感激', null, null, null);
INSERT INTO `word` VALUES ('2128', '71', 'obscure', '[əb\'skjuə, ɔb-]', null, 'a.阴暗，模糊', null, null, null);
INSERT INTO `word` VALUES ('2129', '72', 'extent', '[ik\'stent]', null, 'n.程度，范围，大小，限度', null, null, null);
INSERT INTO `word` VALUES ('2130', '73', 'exterior', '[ik\'stiəriə]', null, 'n.外部，外表 a.外部的，外表的', null, null, null);
INSERT INTO `word` VALUES ('2131', '74', 'external', '[ik\'stə:nəl]', null, 'a.外部的，外表的，外面的', null, null, null);
INSERT INTO `word` VALUES ('2132', '75', 'petrol', '[\'petrəl]', null, 'n.汽油', null, null, null);
INSERT INTO `word` VALUES ('2133', '76', 'petroleum', '[pi\'trəuliəm, pə-]', null, 'n.石油', null, null, null);
INSERT INTO `word` VALUES ('2134', '77', 'delay', '[di\'lei]', null, 'vt./n.推迟，延误，耽搁', null, null, null);
INSERT INTO `word` VALUES ('2135', '78', 'decay', '[di\'kei]', null, 'vi.腐烂，腐朽', null, null, null);
INSERT INTO `word` VALUES ('2136', '79', 'decent', '[\'di:sənt]', null, 'a.像样的，体面的', null, null, null);
INSERT INTO `word` VALUES ('2137', '80', 'route', '[ru:t, raut]', null, 'n.路；路线；航线', null, null, null);
INSERT INTO `word` VALUES ('2138', '81', 'ruin', '[\'ruin, \'ru:-]', null, 'v.毁坏，破坏 n.毁灭，[pl.]废墟', null, null, null);
INSERT INTO `word` VALUES ('2139', '82', 'sake', '[seik]', null, 'n.缘故，理由', null, null, null);
INSERT INTO `word` VALUES ('2140', '83', 'satellite', '[\'sætəlait]', null, 'n.卫星', null, null, null);
INSERT INTO `word` VALUES ('2141', '84', 'scale', '[skeil]', null, 'n.大小，规模；等级；刻度', null, null, null);
INSERT INTO `word` VALUES ('2142', '85', 'temple', '[\'templ]', null, 'n.庙宇', null, null, null);
INSERT INTO `word` VALUES ('2143', '86', 'tedious', '[\'ti:diəs, \'ti:dʒəs]', null, 'a.乏味道，单调的，', null, null, null);
INSERT INTO `word` VALUES ('2144', '87', 'tend', '[tend]', null, 'vi.易于，趋向', null, null, null);
INSERT INTO `word` VALUES ('2145', '88', 'tendency', '[\'tendənsi]', null, 'n.趋向，趋势', null, null, null);
INSERT INTO `word` VALUES ('2146', '89', 'ultimate', '[\'ʌltimət]', null, 'a.极端的，最大的，最终的 n.极端', null, null, null);
INSERT INTO `word` VALUES ('2147', '90', 'undergo', '[,ʌndə\'ɡəu]', null, 'v.经历，遭受', null, null, null);
INSERT INTO `word` VALUES ('2148', '91', 'abundant', '[ə\'bʌndənt]', null, 'a.丰富的，充裕的，大量的', null, null, null);
INSERT INTO `word` VALUES ('2149', '92', 'adopt', '[ə\'dɔpt]', null, 'v.收养；采用；采纳', null, null, null);
INSERT INTO `word` VALUES ('2150', '93', 'adapt', '[ə\'dæpt]', null, 'vi.适应，适合；改编，改写 vt.使适应', null, null, null);
INSERT INTO `word` VALUES ('2151', '94', 'bachelor', '[\'bætʃələ]', null, 'n.学士，学士学位；单身汉', null, null, null);
INSERT INTO `word` VALUES ('2152', '95', 'casual', '[\'kæʒjuəl]', null, 'a.偶然的，碰巧的；临时的；非正式的', null, null, null);
INSERT INTO `word` VALUES ('2153', '96', 'trap', '[træp]', null, 'n.陷阱，圈套 v.设陷阱捕捉', null, null, null);
INSERT INTO `word` VALUES ('2154', '97', 'vacant', '[\'veikənt]', null, 'a.空的，未占用的', null, null, null);
INSERT INTO `word` VALUES ('2155', '98', 'vacuum', '[\'vækjuəm]', null, 'n.真空，真空吸尘器', null, null, null);
INSERT INTO `word` VALUES ('2156', '99', 'oral', '[\'ɔ:rəl, \'ɔ-]', null, 'a.口头的，口述的，口的', null, null, null);
INSERT INTO `word` VALUES ('2157', '100', 'optics', '[\'ɔptiks]', null, 'n.（单、复数同形）光学', null, null, null);
INSERT INTO `word` VALUES ('2158', '101', 'organ', '[\'ɔ:ɡən]', null, 'n.器官，风琴', null, null, null);
INSERT INTO `word` VALUES ('2159', '102', 'excess', '[ik\'ses, \'ek-, \'ekses, ik\'s-]', null, 'n.过分，过量，过剩', null, null, null);
INSERT INTO `word` VALUES ('2160', '103', 'expel', '[ik\'spel]', null, 'v.驱逐，开除，赶出', null, null, null);
INSERT INTO `word` VALUES ('2161', '104', 'expend', '[ik\'spend]', null, 'v.消费', null, null, null);
INSERT INTO `word` VALUES ('2162', '105', 'expenditure', '[iks\'penditʃə]', null, 'n.支出，消费；经费', null, null, null);
INSERT INTO `word` VALUES ('2163', '106', 'expense', '[ik\'spens]', null, 'n.开销，费用', null, null, null);
INSERT INTO `word` VALUES ('2164', '107', 'expensive', '[ik\'spensiv]', null, 'a.花钱多的；价格高贵的', null, null, null);
INSERT INTO `word` VALUES ('2165', '108', 'expand', '[ik\'spænd]', null, 'v.扩大，扩张；展开，膨胀', null, null, null);
INSERT INTO `word` VALUES ('2166', '109', 'expansion', '[ik\'spænʃən]', null, 'n.扩大，扩充；发展，膨胀', null, null, null);
INSERT INTO `word` VALUES ('2167', '110', 'private', '[\'praivit]', null, 'a.私人的，个人的', null, null, null);
INSERT INTO `word` VALUES ('2168', '111', 'individual', '[,indi\'vidjuəl, -dʒəl]', null, 'a.个别的，单独的 n.个人，个体', null, null, null);
INSERT INTO `word` VALUES ('2169', '112', 'personal', '[\'pə:sənl]', null, 'a.个人的，私人的；亲自的', null, null, null);
INSERT INTO `word` VALUES ('2170', '114', 'personnel', '[,pə:sə\'nel]', null, 'n.[总称]人员，员工；人事部门', null, null, null);
INSERT INTO `word` VALUES ('2171', '115', 'the', '[ði]', null, 'Pacific Ocean 太平洋', null, null, null);
INSERT INTO `word` VALUES ('2172', '116', 'the', '[ði]', null, 'Atlantic Ocean 大西洋', null, null, null);
INSERT INTO `word` VALUES ('2173', '117', 'the', '[ði]', null, 'Arctic Ocean 北冰洋', null, null, null);
INSERT INTO `word` VALUES ('2174', '118', 'the', '[ði]', null, 'Antarctic Ocean 南冰洋', null, null, null);
INSERT INTO `word` VALUES ('2175', '119', 'grant', '[ɡrænd]', null, 'vt.授予，同意，准予', null, null, null);
INSERT INTO `word` VALUES ('2176', '119', 'grand', '[ɡrænd]', null, 'a.宏伟大，壮丽的，重大的', null, null, null);
INSERT INTO `word` VALUES ('2177', '120', 'invade', '[in\'veid]', null, 'v.侵入，侵略，侵袭 ', null, null, null);
INSERT INTO `word` VALUES ('2178', '121', 'acid', '[\'æsid]', null, 'n.酸，酸性物质 a.酸的；尖刻的', null, null, null);
INSERT INTO `word` VALUES ('2179', '122', 'acknowledge', '[ək\'nɔlidʒ]', null, 'v.承认；致谢', null, null, null);
INSERT INTO `word` VALUES ('2180', '123', 'balcony', '[\'bælkəni]', null, 'n.阳台', null, null, null);
INSERT INTO `word` VALUES ('2181', '124', 'calculate', '[\'kælkjuleit]', null, 'vt.计算，核算', null, null, null);
INSERT INTO `word` VALUES ('2182', '125', 'calendar', '[\'kælində]', null, 'n.日历，月历', null, null, null);
INSERT INTO `word` VALUES ('2183', '126', 'optimistic', '[,ɔpti\'mistik]', null, 'a.乐观', null, null, null);
INSERT INTO `word` VALUES ('2184', '127', 'optional', '[\'ɔpʃənəl]', null, 'a.可以任选的，非强制的', null, null, null);
INSERT INTO `word` VALUES ('2185', '128', 'outstanding', '[,aut\'stændiŋ]', null, 'a.杰出的，突出的，显著的', null, null, null);
INSERT INTO `word` VALUES ('2186', '129', 'export', '[ik\'spɔ:t, \'eks-, \'ekspɔ:t]', null, 'n.出口（物） v.出口，输出', null, null, null);
INSERT INTO `word` VALUES ('2187', '130', 'import', '[im\'pɔ:t, \'impɔ:t]', null, 'n.进口（物） v.进口，输入', null, null, null);
INSERT INTO `word` VALUES ('2188', '131', 'impose', '[im\'pəuz]', null, 'vt.把...加强(on)；采用，利用', null, null, null);
INSERT INTO `word` VALUES ('2189', '132', 'religion', '[ri\'lidʒən]', null, 'n.宗教，宗教信仰', null, null, null);
INSERT INTO `word` VALUES ('2190', '133', 'religious', '[ri\'lidʒəs]', null, 'a.宗教的', null, null, null);
INSERT INTO `word` VALUES ('2191', '134', 'victim', '[\'viktim]', null, 'n.牺牲品，受害者', null, null, null);
INSERT INTO `word` VALUES ('2192', '135', 'video', '[\'vidiəu]', null, 'n.电视，视频 a.电视的，录像的', null, null, null);
INSERT INTO `word` VALUES ('2193', '136', 'videotape', '[\'vidiəuteip]', null, 'n.录像磁带 v.把...录在录像带上', null, null, null);
INSERT INTO `word` VALUES ('2194', '137', 'offend', '[ə\'fend]', null, 'v.冒犯，触犯', null, null, null);
INSERT INTO `word` VALUES ('2195', '138', 'bother', '[\'bɔðə]', null, 'v.打搅，麻烦', null, null, null);
INSERT INTO `word` VALUES ('2196', '139', 'interfere', '[,intə\'fiə]', null, 'v.干涉，干扰，妨碍', null, null, null);
INSERT INTO `word` VALUES ('2197', '140', 'internal', '[in\'tə:nəl]', null, 'a.内部的，国内的', null, null, null);
INSERT INTO `word` VALUES ('2198', '141', 'beforehand', '[bi\'fɔ:hænd]', null, 'ad.预先，事先', null, null, null);
INSERT INTO `word` VALUES ('2199', '142', 'racial', '[\'reiʃəl]', null, 'a.人种的种族的', null, null, null);
INSERT INTO `word` VALUES ('2200', '143', 'radiation', '[,reidi\'eiʃən]', null, 'n.放射物，辐射', null, null, null);
INSERT INTO `word` VALUES ('2201', '144', 'radical', '[\'rædikəl]', null, 'a.根本的；激进的', null, null, null);
INSERT INTO `word` VALUES ('2202', '145', 'range', '[reindʒ]', null, 'n.幅度，范围 v.（在某范围内）变动', null, null, null);
INSERT INTO `word` VALUES ('2203', '146', 'wonder', '[\'wʌndə]', null, 'n.惊奇，奇迹 v.想知道，对...感到疑惑', null, null, null);
INSERT INTO `word` VALUES ('2204', '147', 'isolate', '[\'aisəleit, -lit]', null, 'vt.使隔离，使孤立', null, null, null);
INSERT INTO `word` VALUES ('2205', '148', 'issue', '[\'iʃju:, \'isju:]', null, 'n.问题，争论点；发行，（报刊）一期', null, null, null);
INSERT INTO `word` VALUES ('2206', '149', 'hollow', '[\'hɔləu]', null, 'a.空的，中空的，空虚道', null, null, null);
INSERT INTO `word` VALUES ('2207', '150', 'hook', '[huk]', null, 'n.钩 vt.钩住', null, null, null);
INSERT INTO `word` VALUES ('2208', '151', 'adequate', '[\'ædikwit]', null, 'a.适当地；足够', null, null, null);
INSERT INTO `word` VALUES ('2209', '152', 'adhere', '[əd\'hiə]', null, 'vi.粘附，附着；遵守，坚持', null, null, null);
INSERT INTO `word` VALUES ('2210', '153', 'ban', '[bæn]', null, 'vt.取缔，禁止', null, null, null);
INSERT INTO `word` VALUES ('2211', '154', 'capture', '[\'kæptʃə]', null, 'vt.俘虏，捕获', null, null, null);
INSERT INTO `word` VALUES ('2212', '155', 'valid', '[\'vælid]', null, 'a.有效的，有根据的；正当的', null, null, null);
INSERT INTO `word` VALUES ('2213', '156', 'valley', '[\'væli]', null, 'n.山谷，峡谷', null, null, null);
INSERT INTO `word` VALUES ('2214', '157', 'consistent', '[kən\'sistənt]', null, 'a.坚固定；一致的，始终如一的', null, null, null);
INSERT INTO `word` VALUES ('2215', '158', 'continuous', '[kən\'tɪnjʊəs]', null, 'a.继续的，连续（不断）的', null, null, null);
INSERT INTO `word` VALUES ('2216', '159', 'continual', '[kən\'tinjuəl]', null, 'a.不断地，频繁的', null, null, null);
INSERT INTO `word` VALUES ('2217', '160', 'explode', '[ik\'spləud]', null, 'v.爆炸；爆发；激增', null, null, null);
INSERT INTO `word` VALUES ('2218', '161', 'exploit', '[\'eksplɔit, ik\'s-]', null, 'v.剥削；利用，开采', null, null, null);
INSERT INTO `word` VALUES ('2219', '162', 'explore', '[ik\'splɔ:]', null, 'v.勘探', null, null, null);
INSERT INTO `word` VALUES ('2220', '163', 'explosion', '[ik\'spləuʒən]', null, 'n.爆炸；爆发；激增', null, null, null);
INSERT INTO `word` VALUES ('2221', '164', 'explosive', '[ik\'spləusiv]', null, 'a.爆炸的；极易引起争论的', null, null, null);
INSERT INTO `word` VALUES ('2222', '165', 'remote', '[ri\'məut]', null, 'a.遥远的，偏僻的', null, null, null);
INSERT INTO `word` VALUES ('2223', '166', 'removal', '[ri\'mu:vəl]', null, 'n.除去，消除', null, null, null);
INSERT INTO `word` VALUES ('2224', '167', 'render', '[\'rendə]', null, 'vt.使得，致使', null, null, null);
INSERT INTO `word` VALUES ('2225', '168', 'precaution', '[pri\'kɔ:ʃən]', null, 'n.预防，防备，警惕', null, null, null);
INSERT INTO `word` VALUES ('2226', '169', 'idle', '[\'aidl]', null, 'a.懒散的，无所事事的', null, null, null);
INSERT INTO `word` VALUES ('2227', '170', 'identify', '[ai\'dentifai]', null, 'vt.认出，鉴定', null, null, null);
INSERT INTO `word` VALUES ('2228', '171', 'identify', '[ai\'dentifai]', null, 'n.身份；个性，特性', null, null, null);
INSERT INTO `word` VALUES ('2229', '172', 'poverty', '[\'pɔvəti]', null, 'n.贫穷', null, null, null);
INSERT INTO `word` VALUES ('2230', '173', 'resistant', '[ri\'zistənt]', null, 'a.(to)抵抗的，抗...的，耐...的', null, null, null);
INSERT INTO `word` VALUES ('2231', '174', 'resolve', '[ri\'zɔlv]', null, 'vt.解决；决定，决意', null, null, null);
INSERT INTO `word` VALUES ('2232', '175', 'barrel', '[\'bærəl]', null, 'n.桶', null, null, null);
INSERT INTO `word` VALUES ('2233', '176', 'bargain', '[\'bɑ:ɡin]', null, 'n.便宜货 vi.讨价还价', null, null, null);
INSERT INTO `word` VALUES ('2234', '177', 'coarse', '[kɔ:s]', null, 'a.粗的，粗糙的，粗劣的', null, null, null);
INSERT INTO `word` VALUES ('2235', '178', 'coach', '[kəutʃ]', null, 'n.教练；长途公共汽车', null, null, null);
INSERT INTO `word` VALUES ('2236', '179', 'code', '[kəud]', null, 'n.准则，法规，密码', null, null, null);
INSERT INTO `word` VALUES ('2237', '180', 'coil', '[kɔil]', null, 'n.线圈 v.卷，盘绕 ', null, null, null);
INSERT INTO `word` VALUES ('2238', '181', 'adult', '[\'ædʌlt, ə\'dʌlt]', null, 'n.成年人', null, null, null);
INSERT INTO `word` VALUES ('2239', '182', 'advertise', '[\'ædvətaiz]', null, 'v.为...做广告', null, null, null);
INSERT INTO `word` VALUES ('2240', '183', 'advertisement', '[əd\'və:tismənt, ,ædvə\'taizmənt]', null, 'n.广告', null, null, null);
INSERT INTO `word` VALUES ('2241', '184', 'agency', '[\'eidʒənsi]', null, 'n.代理商，经销商', null, null, null);
INSERT INTO `word` VALUES ('2242', '185', 'focus', '[\'fəukəs]', null, 'v.（使）聚集 n.焦点，中心，聚焦', null, null, null);
INSERT INTO `word` VALUES ('2243', '186', 'forbid', '[fə\'bid]', null, 'vt.不许，禁止', null, null, null);
INSERT INTO `word` VALUES ('2244', '187', 'debate', '[di\'beit]', null, 'n./v.辩论，争论', null, null, null);
INSERT INTO `word` VALUES ('2245', '188', 'debt', '[det]', null, 'n.欠债', null, null, null);
INSERT INTO `word` VALUES ('2246', '189', 'decade', '[\'dekeid]', null, 'n.十年', null, null, null);
INSERT INTO `word` VALUES ('2247', '190', 'enclose', '[in\'kləuz]', null, 'vt.围住；把...装入信封', null, null, null);
INSERT INTO `word` VALUES ('2248', '191', 'encounter', '[in\'kauntə]', null, 'vt./n.遭遇，遭到', null, null, null);
INSERT INTO `word` VALUES ('2249', '192', 'globe', '[ɡləub]', null, 'n.地球，世界；地球仪', null, null, null);
INSERT INTO `word` VALUES ('2250', '193', 'global', '[\'ɡləubəl]', null, 'a.全球的；总的', null, null, null);
INSERT INTO `word` VALUES ('2251', '194', 'scan', '[skæn]', null, 'vt.细看；扫描；浏览', null, null, null);
INSERT INTO `word` VALUES ('2252', '195', 'scandal', '[\'skændəl]', null, 'n.丑事，丑闻', null, null, null);
INSERT INTO `word` VALUES ('2253', '196', 'significance', '[siɡ\'nifikəns]', null, 'n.意义；重要性', null, null, null);
INSERT INTO `word` VALUES ('2254', '197', 'subsequent', '[\'sʌbsikwənt]', null, 'a.随后的，后来的', null, null, null);
INSERT INTO `word` VALUES ('2255', '198', 'virtue', '[\'və:tju:]', null, 'n.美德，优点', null, null, null);
INSERT INTO `word` VALUES ('2256', '199', 'virtual', '[\'və:tʃuəl]', null, 'a.实际上的，事实上的', null, null, null);
INSERT INTO `word` VALUES ('2257', '200', 'orient', '[\'ɔ:riənt, \'əu-, \'ɔ:rient]', null, 'vt.使适应，(to,toward)使朝向 n.东方', null, null, null);
INSERT INTO `word` VALUES ('2258', '201', 'portion', '[\'pɔ:ʃən, \'pəu-]', null, 'n.一部分', null, null, null);
INSERT INTO `word` VALUES ('2259', '202', 'target', '[\'tɑ:ɡit]', null, 'n.目标，靶子 vt.瞄准', null, null, null);
INSERT INTO `word` VALUES ('2260', '203', 'portable', '[\'pɔ:təbl, \'pəu-]', null, 'a.手提式的', null, null, null);
INSERT INTO `word` VALUES ('2261', '204', 'decline', '[di\'klain]', null, 'v.拒绝，谢绝；下降', null, null, null);
INSERT INTO `word` VALUES ('2262', '205', 'illusion', '[i\'lju:ʒən]', null, 'n.错觉', null, null, null);
INSERT INTO `word` VALUES ('2263', '206', 'likelihood', '[\'laiklihud]', null, 'n.可能，可能性', null, null, null);
INSERT INTO `word` VALUES ('2264', '207', 'stripe', '[straip]', null, 'n.条纹', null, null, null);
INSERT INTO `word` VALUES ('2265', '208', 'emphasize', '[\'emfəsaiz]', null, 'vt.强调，着重', null, null, null);
INSERT INTO `word` VALUES ('2266', '209', 'emotion', '[i\'məuʃən]', null, 'n.情感，感情', null, null, null);
INSERT INTO `word` VALUES ('2267', '210', 'emotional', '[i\'məuʃənəl]', null, 'a.感情的，情绪（上）的 ', null, null, null);
INSERT INTO `word` VALUES ('2268', '211', 'awful', '[\'ɔːfʊl]', null, 'a.极坏的，威严的，可怕的', null, null, null);
INSERT INTO `word` VALUES ('2269', '212', 'awkward', '[\'ɔ:kwəd]', null, 'a.笨拙的，棘手的', null, null, null);
INSERT INTO `word` VALUES ('2270', '213', 'clue', '[klu:]', null, 'n.线索，提示', null, null, null);
INSERT INTO `word` VALUES ('2271', '214', 'collision', '[kə\'lɪʒ(ə)n]', null, 'n.碰撞，冲突', null, null, null);
INSERT INTO `word` VALUES ('2272', '215', 'device', '[di\'vais]', null, 'n.装置，设备', null, null, null);
INSERT INTO `word` VALUES ('2273', '216', 'devise', '[di\'vaiz]', null, 'vt.发明，策划，想出', null, null, null);
INSERT INTO `word` VALUES ('2274', '217', 'inevitable', '[in\'evitəbl]', null, 'a.不可避免的', null, null, null);
INSERT INTO `word` VALUES ('2275', '218', 'naval', '[\'neivəl]', null, 'a.海军的', null, null, null);
INSERT INTO `word` VALUES ('2276', '219', 'navigation', '[,nævi\'ɡeiʃən]', null, 'n.航行', null, null, null);
INSERT INTO `word` VALUES ('2277', '220', 'necessity', '[ni\'sesəti, nə-]', null, 'n.必需品；必要性', null, null, null);
INSERT INTO `word` VALUES ('2278', '221', 'previous', '[\'pri:vjəs]', null, 'a.先，前，以前的', null, null, null);
INSERT INTO `word` VALUES ('2279', '222', 'provision', '[prəu\'viʒən]', null, 'n.[pl.]给养，口粮；准备，设备，装置', null, null, null);
INSERT INTO `word` VALUES ('2280', '223', 'pursue', '[pə\'sju:, -\'su:]', null, 'vt.追逐；追求；从事，进行', null, null, null);
INSERT INTO `word` VALUES ('2281', '224', 'stale', '[steil]', null, 'a.不新鲜的，陈腐的', null, null, null);
INSERT INTO `word` VALUES ('2282', '225', 'substitute', '[\'sʌbstitju:t, -tu:t]', null, 'n.代用品 vt.代替', null, null, null);
INSERT INTO `word` VALUES ('2283', '226', 'deserve', '[di\'zə:v]', null, 'vt.应受，应得，值得', null, null, null);
INSERT INTO `word` VALUES ('2284', '227', 'discrimination', '[dis,krimi\'neiʃən]', null, 'n.歧视；辨别力', null, null, null);
INSERT INTO `word` VALUES ('2285', '228', 'professional', '[prəu\'feʃənəl]', null, 'a.职业的，专门的', null, null, null);
INSERT INTO `word` VALUES ('2286', '229', 'secure', '[si\'kjuə]', null, 'a.安全的，可靠的', null, null, null);
INSERT INTO `word` VALUES ('2287', '230', 'security', '[si\'kjuəriti]', null, 'n.安全，保障', null, null, null);
INSERT INTO `word` VALUES ('2288', '231', 'scratch', '[skrætʃ]', null, 'v./n.抓，搔，扒', null, null, null);
INSERT INTO `word` VALUES ('2289', '232', 'talent', '[\'tælənt]', null, 'n.才能，天资；人才', null, null, null);
INSERT INTO `word` VALUES ('2290', '233', 'insurance', '[in\'ʃuərəns]', null, 'n.保险，保险费', null, null, null);
INSERT INTO `word` VALUES ('2291', '234', 'insure', '[in\'ʃuə]', null, 'vt.给...保险，保证，确保', null, null, null);
INSERT INTO `word` VALUES ('2292', '235', 'nevertheless', '[,nevəðə\'les]', null, 'ad.仍然，然而，不过', null, null, null);
INSERT INTO `word` VALUES ('2293', '236', 'neutral', '[\'nju:trəl]', null, 'a.中立的，中性的', null, null, null);
INSERT INTO `word` VALUES ('2294', '237', 'spot', '[spɔt]', null, 'n.地点；斑点 vt.认出，发现；玷污', null, null, null);
INSERT INTO `word` VALUES ('2295', '238', 'spray', '[sprei]', null, 'v.喷，（使）溅散', null, null, null);
INSERT INTO `word` VALUES ('2296', '239', 'medium', '[\'mi:diəm, -djəm]', null, 'a.中等的，适中的 n.媒介物，新闻媒介', null, null, null);
INSERT INTO `word` VALUES ('2297', '240', 'media', '[\'mi:diə]', null, 'n.新闻传媒', null, null, null);
INSERT INTO `word` VALUES ('2298', '241', 'auxiliary', '[ɔ:ɡ\'ziljəri]', null, 'a.辅助的，备用的', null, null, null);
INSERT INTO `word` VALUES ('2299', '242', 'automatic', '[,ɔ:tə\'mætik]', null, 'a.自动的', null, null, null);
INSERT INTO `word` VALUES ('2300', '243', 'compete', '[kəm\'pi:t]', null, 'vi.竞争，比赛', null, null, null);
INSERT INTO `word` VALUES ('2301', '244', 'competent', '[\'kɔmpitənt]', null, 'a.有能力的，能胜任的', null, null, null);
INSERT INTO `word` VALUES ('2302', '245', 'competition', '[,kɔmpi\'tiʃən]', null, 'n.竞争，比赛', null, null, null);
INSERT INTO `word` VALUES ('2303', '246', 'distribute', '[di\'stribju:t, \'dis-]', null, 'vt.分发', null, null, null);
INSERT INTO `word` VALUES ('2304', '247', 'disturb', '[dis\'tə:b]', null, 'vt.打搅，妨碍', null, null, null);
INSERT INTO `word` VALUES ('2305', '248', 'infer', '[in\'fə:]', null, 'v.推论，推断', null, null, null);
INSERT INTO `word` VALUES ('2306', '249', 'integrate', '[\'intiɡreit, \'intiɡrit, -ɡreit]', null, 'v.(into,with)（使）成为一体，（使）合并', null, null, null);
INSERT INTO `word` VALUES ('2307', '250', 'moist', '[mɔist]', null, 'a.潮湿', null, null, null);
INSERT INTO `word` VALUES ('2308', '251', 'moisture', '[\'mɔistʃə]', null, 'n.潮湿', null, null, null);
INSERT INTO `word` VALUES ('2309', '252', 'promote', '[prəu\'məut]', null, 'vt.促进；提升', null, null, null);
INSERT INTO `word` VALUES ('2310', '253', 'region', '[\'ri:dʒən]', null, 'n.地区；范围；幅度', null, null, null);
INSERT INTO `word` VALUES ('2311', '254', 'register', '[\'redʒistə]', null, 'v./n.登记，注册', null, null, null);
INSERT INTO `word` VALUES ('2312', '255', 'stable', '[\'steibl]', null, 'a.稳定的', null, null, null);
INSERT INTO `word` VALUES ('2313', '256', 'sophisticated', '[sə\'fistikeitid]', null, 'a.老于世故的，老练的；很复杂的', null, null, null);
INSERT INTO `word` VALUES ('2314', '257', 'splendid', '[\'splendid]', null, 'a.极好的，壮丽的，辉煌的', null, null, null);
INSERT INTO `word` VALUES ('2315', '258', 'cancel', '[\'kænsəl]', null, 'vt.取消，废除', null, null, null);
INSERT INTO `word` VALUES ('2316', '259', 'variable', '[\'vεəriəbl]', null, 'a.易变的，可变的', null, null, null);
INSERT INTO `word` VALUES ('2317', '260', 'prospect', '[\'prɔspekt]', null, 'n.前景，前途；景象', null, null, null);
INSERT INTO `word` VALUES ('2318', '261', 'prosperity', '[prɔs\'periti]', null, 'n.兴旺，繁荣', null, null, null);
INSERT INTO `word` VALUES ('2319', '262', 'aspect', '[\'æspekt]', null, 'n.方面；朝向；面貌', null, null, null);
INSERT INTO `word` VALUES ('2320', '263', 'cope', '[kəup]', null, 'vi.(with)（成功地）应付，处理', null, null, null);
INSERT INTO `word` VALUES ('2321', '264', 'core', '[kɔ:]', null, 'n.果心，核心', null, null, null);
INSERT INTO `word` VALUES ('2322', '265', 'maintain', '[mein\'tein]', null, 'vt.维持，保持；坚持，主张', null, null, null);
INSERT INTO `word` VALUES ('2323', '266', 'mainland', '[\'meinlənd]', null, 'n.大陆', null, null, null);
INSERT INTO `word` VALUES ('2324', '267', 'discipline', '[\'disiplin]', null, 'n.纪律；惩罚；学科', null, null, null);
INSERT INTO `word` VALUES ('2325', '268', 'domestic', '[dəu\'mestik]', null, 'a.本国的，国内的；家用的；家庭的', null, null, null);
INSERT INTO `word` VALUES ('2326', '269', 'constant', '[\'kɔnstənt]', null, 'a.不变的，恒定的 n.常数 ', null, null, null);
INSERT INTO `word` VALUES ('2327', '270', 'cliff', '[klif]', null, 'n.悬崖，峭壁 ', null, null, null);
INSERT INTO `word` VALUES ('2328', '271', 'authority', '[ɔ:\'θɔrəti]', null, 'n.权威；当局', null, null, null);
INSERT INTO `word` VALUES ('2329', '272', 'audio', '[\'ɔ:diəu]', null, 'a.听觉', null, null, null);
INSERT INTO `word` VALUES ('2330', '273', 'attitude', '[\'ætitju:d, -tu:d]', null, 'n.态度', null, null, null);
INSERT INTO `word` VALUES ('2331', '274', 'community', '[kə\'mju:niti]', null, 'n.社区，社会', null, null, null);
INSERT INTO `word` VALUES ('2332', '275', 'commit', '[kə\'mit]', null, 'vt.犯（错误，罪行等），干（坏事等）', null, null, null);
INSERT INTO `word` VALUES ('2333', '276', 'comment', '[\'kɔment]', null, 'n./vt.评论', null, null, null);
INSERT INTO `word` VALUES ('2334', '277', 'distinguish', '[dis\'tiŋɡwiʃ]', null, 'vt.区分，辨别', null, null, null);
INSERT INTO `word` VALUES ('2335', '278', 'distress', '[di\'stres]', null, 'n.痛苦，悲伤 vt.使痛苦', null, null, null);
INSERT INTO `word` VALUES ('2336', '279', 'facility', '[fə\'siliti]', null, 'n.[pl.] 设备，设施；便利，方便', null, null, null);
INSERT INTO `word` VALUES ('2337', '280', 'faculty', '[\'fækəlti]', null, 'n.能力，技能；系，学科，学院；全体教员', null, null, null);
INSERT INTO `word` VALUES ('2338', '281', 'mixture', '[\'mikstʃə]', null, 'n.混合，混合物', null, null, null);
INSERT INTO `word` VALUES ('2339', '282', 'mood', '[mu:d]', null, 'n.心情，情绪；语气', null, null, null);
INSERT INTO `word` VALUES ('2340', '283', 'moral', '[\'mɔrəl, \'mɔ:-]', null, 'a.道德上的，有道德的', null, null, null);
INSERT INTO `word` VALUES ('2341', '284', 'prominent', '[\'prɔminənt]', null, 'a.突出的', null, null, null);
INSERT INTO `word` VALUES ('2342', '285', 'substance', '[\'sʌbstəns]', null, 'n.物质；实质', null, null, null);
INSERT INTO `word` VALUES ('2343', '286', 'substantial', '[səb\'stænʃəl]', null, 'a.可观的；牢固的；实质的', null, null, null);
INSERT INTO `word` VALUES ('2344', '287', 'prompt', '[prɔmpt]', null, 'vt.促使 a.敏捷的，及时的', null, null, null);
INSERT INTO `word` VALUES ('2345', '288', 'vivid', '[\'vivid]', null, 'a.生动的', null, null, null);
INSERT INTO `word` VALUES ('2346', '289', 'vocabulary', '[vəu\'kæbjuləri]', null, 'n.词汇（量）；词汇表', null, null, null);
INSERT INTO `word` VALUES ('2347', '290', 'venture', '[\'ventʃə]', null, 'n.风险投资，风险项目 v.冒险；取于', null, null, null);
INSERT INTO `word` VALUES ('2348', '291', 'version', '[\'və:ʃən]', null, 'n.版本，译本；说法', null, null, null);
INSERT INTO `word` VALUES ('2349', '292', 'waist', '[weist]', null, 'n.腰，腰部', null, null, null);
INSERT INTO `word` VALUES ('2350', '293', 'weld', '[weld]', null, 'v./n.焊接', null, null, null);
INSERT INTO `word` VALUES ('2351', '294', 'yawn', '[jɔ:n]', null, 'vi.打哈欠', null, null, null);
INSERT INTO `word` VALUES ('2352', '295', 'yield', '[ji:ld]', null, 'vi.(to)屈服于；让出，放弃 n.产量', null, null, null);
INSERT INTO `word` VALUES ('2353', '296', 'zone', '[zəun]', null, 'n.地区，区域', null, null, null);
INSERT INTO `word` VALUES ('2354', '297', 'strategy', '[\'strætidʒi]', null, 'n.战略，策略', null, null, null);
INSERT INTO `word` VALUES ('2355', '298', 'strategic', '[strə\'ti:dʒik]', null, 'a.战略（上）的，关键的', null, null, null);
INSERT INTO `word` VALUES ('2356', '299', 'tense', '[tens]', null, 'a.紧张的 v.拉紧 n.时态', null, null, null);
INSERT INTO `word` VALUES ('2357', '300', 'tension', '[\'tenʃən]', null, 'n.紧张（状态），张力 ', null, null, null);
INSERT INTO `word` VALUES ('2358', '301', 'avenue', '[\'ævənju:]', null, 'n.林荫道，大街', null, null, null);
INSERT INTO `word` VALUES ('2359', '302', 'available', '[ə\'veiləbl]', null, 'a.现成可用的；可得到的', null, null, null);
INSERT INTO `word` VALUES ('2360', '303', 'comparable', '[\'kɔmpərəbl]', null, 'a.(with,to)可比较的，类似的', null, null, null);
INSERT INTO `word` VALUES ('2361', '304', 'comparative', '[kəm\'pærətiv]', null, 'a.比较的，相对的', null, null, null);
INSERT INTO `word` VALUES ('2362', '305', 'dash', '[dæʃ]', null, 'vi.猛冲，飞奔', null, null, null);
INSERT INTO `word` VALUES ('2363', '306', 'data', '[\'deitə]', null, 'n.数据，资料', null, null, null);
INSERT INTO `word` VALUES ('2364', '307', 'dive', '[\'di:vei, daiv]', null, 'vi.跳水，潜水', null, null, null);
INSERT INTO `word` VALUES ('2365', '308', 'diverse', '[dai\'və:s, di-]', null, 'a.不同的，多种多样的', null, null, null);
INSERT INTO `word` VALUES ('2366', '309', 'entitle', '[in\'taitl]', null, 'vt.给...权利，给...资格', null, null, null);
INSERT INTO `word` VALUES ('2367', '310', 'regulate', '[\'reɡjuleit]', null, 'vt.管理，调节', null, null, null);
INSERT INTO `word` VALUES ('2368', '311', 'release', '[ri\'li:s]', null, 'vt./n.释放，排放；解释解脱', null, null, null);
INSERT INTO `word` VALUES ('2369', '312', 'exaggerate', '[iɡ\'zædʒəreit]', null, 'v.夸大，夸张', null, null, null);
INSERT INTO `word` VALUES ('2370', '313', 'evil', '[\'i:vəl]', null, 'a.邪恶的，坏的', null, null, null);
INSERT INTO `word` VALUES ('2371', '314', 'shrink', '[ʃriŋk]', null, 'vi.起皱，收缩；退缩', null, null, null);
INSERT INTO `word` VALUES ('2372', '315', 'subtract', '[səb\'trækt]', null, 'v.减（去）', null, null, null);
INSERT INTO `word` VALUES ('2373', '316', 'suburb', '[\'sʌbə:b]', null, 'n.市郊', null, null, null);
INSERT INTO `word` VALUES ('2374', '317', 'subway', '[\'sʌbwei]', null, 'n.地铁', null, null, null);
INSERT INTO `word` VALUES ('2375', '318', 'survey', '[sə:\'vei, \'sə:vei, sə-]', null, 'n./vt.调查，勘测', null, null, null);
INSERT INTO `word` VALUES ('2376', '319', 'wealthy', '[\'welθi]', null, 'a.富裕的', null, null, null);
INSERT INTO `word` VALUES ('2377', '320', 'adjust', '[ə\'dʒʌst]', null, 'v.调整，调节', null, null, null);
INSERT INTO `word` VALUES ('2378', '321', 'attach', '[ə\'tætʃ]', null, 'vt.系，贴；使附属', null, null, null);
INSERT INTO `word` VALUES ('2379', '322', 'profit', '[\'prɔfit]', null, 'n.利润，益处；v.有益于，有利于', null, null, null);
INSERT INTO `word` VALUES ('2380', '323', 'profitable', '[\'prɔfitəbl]', null, 'a.有利可图的', null, null, null);
INSERT INTO `word` VALUES ('2381', '324', 'slope', '[sləup]', null, 'n.斜坡，斜面', null, null, null);
INSERT INTO `word` VALUES ('2382', '325', 'reinforce', '[,ri:in\'fɔ:s]', null, 'vt.增强，加强', null, null, null);
INSERT INTO `word` VALUES ('2383', '326', 'reject', '[ri\'dʒekt]', null, 'vt.拒绝', null, null, null);
INSERT INTO `word` VALUES ('2384', '327', 'fatal', '[\'feitl]', null, 'a.致命的；重大的', null, null, null);
INSERT INTO `word` VALUES ('2385', '328', 'fate', '[\'feit]', null, 'n.命运', null, null, null);
INSERT INTO `word` VALUES ('2386', '329', 'humble', '[\'hʌmbl]', null, 'a.谦逊的；谦虚的', null, null, null);
INSERT INTO `word` VALUES ('2387', '330', 'illegal', '[ɪ\'liːg(ə)l]', null, 'a.不合法的，非法的 ', null, null, null);
INSERT INTO `word` VALUES ('2388', '331', 'award', '[ə\'wɔ:d]', null, 'vt.授予，判给 n.奖品，奖金', null, null, null);
INSERT INTO `word` VALUES ('2389', '332', 'aware', '[ə\'wεə]', null, 'a.意识到', null, null, null);
INSERT INTO `word` VALUES ('2390', '333', 'column', '[\'kɔləm]', null, 'n.柱，圆柱；栏，专栏', null, null, null);
INSERT INTO `word` VALUES ('2391', '334', 'comedy', '[\'kɔmidi]', null, 'n.喜剧', null, null, null);
INSERT INTO `word` VALUES ('2392', '335', 'dumb', '[dʌm]', null, 'a.哑的；沉默的', null, null, null);
INSERT INTO `word` VALUES ('2393', '336', 'dump', '[dʌmp]', null, 'vt.倾卸，倾倒', null, null, null);
INSERT INTO `word` VALUES ('2394', '337', 'deaf', '[def]', null, 'a.聋的；不愿听的', null, null, null);
INSERT INTO `word` VALUES ('2395', '338', 'decorate', '[\'dekəreit]', null, 'vt.装饰，装璜', null, null, null);
INSERT INTO `word` VALUES ('2396', '339', 'principal', '[\'prinsəpəl]', null, 'a.最重要的 n.负责人，校长', null, null, null);
INSERT INTO `word` VALUES ('2397', '340', 'principle', '[\'prinsəpl]', null, 'n.原则，原理', null, null, null);
INSERT INTO `word` VALUES ('2398', '341', 'prior', '[\'praiə]', null, 'a.优先的，在前的', null, null, null);
INSERT INTO `word` VALUES ('2399', '342', 'priority', '[prai\'ɔrəti]', null, 'n.优先，重点', null, null, null);
INSERT INTO `word` VALUES ('2400', '343', 'prohibit', '[prəu\'hibit]', null, 'vt.禁止，不准', null, null, null);
INSERT INTO `word` VALUES ('2401', '344', 'remarkable', '[ri\'mɑ:kəbl]', null, 'a.值得注意的，异常的，非凡的', null, null, null);
INSERT INTO `word` VALUES ('2402', '345', 'remedy', '[\'remidi]', null, 'n./vt.补救，医治，治疗', null, null, null);
INSERT INTO `word` VALUES ('2403', '346', 'repetition', '[,repi\'tiʃən]', null, 'n.重复，反复', null, null, null);
INSERT INTO `word` VALUES ('2404', '347', 'vain', '[vein]', null, 'a.徒劳的，无效的', null, null, null);
INSERT INTO `word` VALUES ('2405', '348', 'undertake', '[,ʌndə\'teik]', null, 'vt.承担，着手做；同意，答应', null, null, null);
INSERT INTO `word` VALUES ('2406', '349', 'unique', '[ju:\'ni:k]', null, 'a.唯一的，独特的', null, null, null);
INSERT INTO `word` VALUES ('2407', '350', 'obstacle', '[\'ɔbstəkl]', null, 'n.障碍（物），妨碍', null, null, null);
INSERT INTO `word` VALUES ('2408', '351', 'odd', '[ɔd]', null, 'a.奇特的，古怪的；奇数的', null, null, null);
INSERT INTO `word` VALUES ('2409', '352', 'omit', '[əu\'mit]', null, 'vt.省略', null, null, null);
INSERT INTO `word` VALUES ('2410', '353', 'opponent', '[ə\'pəunənt]', null, 'n.敌手，对手', null, null, null);
INSERT INTO `word` VALUES ('2411', '354', 'opportunity', '[,ɔpə\'tju:niti]', null, 'n.机会，时机', null, null, null);
INSERT INTO `word` VALUES ('2412', '355', 'orchestra', '[\'ɔ:kistrə, -kes-]', null, 'n.管弦乐队', null, null, null);
INSERT INTO `word` VALUES ('2413', '356', 'semester', '[si\'mestə]', null, 'n.学期；半年', null, null, null);
INSERT INTO `word` VALUES ('2414', '357', 'semiconductor', '[,semikən\'dɔktə, ,semai-]', null, 'n.半导体', null, null, null);
INSERT INTO `word` VALUES ('2415', '358', 'seminar', '[\'seminɑ:]', null, 'n.研讨会', null, null, null);
INSERT INTO `word` VALUES ('2416', '359', 'terminal', '[\'tə:minəl]', null, 'a.末端的，极限的 n.终点', null, null, null);
INSERT INTO `word` VALUES ('2417', '360', 'territory', '[\'teritəri]', null, 'n.领土', null, null, null);
INSERT INTO `word` VALUES ('2418', '361', 'approximate', '[ə\'prɒksɪmət]', null, 'a.大概的，大约 v.近似', null, null, null);
INSERT INTO `word` VALUES ('2419', '362', 'arbitrary', '[\'ɑ:bitrəri]', null, 'a.随意的，未断的', null, null, null);
INSERT INTO `word` VALUES ('2420', '363', 'architect', '[\'ɑ:kitekt]', null, 'n.建筑师', null, null, null);
INSERT INTO `word` VALUES ('2421', '364', 'architecture', '[\'ɑ:kitektʃə]', null, 'n.建筑学', null, null, null);
INSERT INTO `word` VALUES ('2422', '365', 'biology', '[bai\'ɔlədʒi]', null, 'n.生物学', null, null, null);
INSERT INTO `word` VALUES ('2423', '366', 'geography', '[dʒi\'ɔɡrəfi]', null, 'n.地理（学）', null, null, null);
INSERT INTO `word` VALUES ('2424', '367', 'geology', '[dʒi\'ɔlədʒi]', null, 'n.地质学', null, null, null);
INSERT INTO `word` VALUES ('2425', '368', 'geometry', '[dʒi\'ɔmitri]', null, 'n.几何（学）', null, null, null);
INSERT INTO `word` VALUES ('2426', '369', 'arithmetic', '[ə\'rɪθmətɪk]', null, 'n.算术', null, null, null);
INSERT INTO `word` VALUES ('2427', '370', 'algebra', '[\'ældʒibrə]', null, 'n.代数', null, null, null);
INSERT INTO `word` VALUES ('2428', '371', 'entertainment', '[,entə\'teinmənt]', null, 'n.娱乐；招待，款待', null, null, null);
INSERT INTO `word` VALUES ('2429', '372', 'enthusiasm', '[in\'θju:ziæzəm, in\'θu:-]', null, 'n.热情，热心', null, null, null);
INSERT INTO `word` VALUES ('2430', '373', 'entry', '[\'entri]', null, 'n.进入，入口处；参赛的人（或物）', null, null, null);
INSERT INTO `word` VALUES ('2431', '374', 'environment', '[ɪn\'vaɪrənm(ə)nt; en-]', null, 'n.环境', null, null, null);
INSERT INTO `word` VALUES ('2432', '375', 'episode', '[\'episəud]', null, 'n.插曲，片段', null, null, null);
INSERT INTO `word` VALUES ('2433', '376', 'equation', '[i\'kweiʒən, -ʃən]', null, 'n.方程（式）', null, null, null);
INSERT INTO `word` VALUES ('2434', '377', 'restrain', '[ri\'strein]', null, 'vt.阻止，抑制', null, null, null);
INSERT INTO `word` VALUES ('2435', '378', 'restraint', '[ri\'streint]', null, 'n.抑制，限制', null, null, null);
INSERT INTO `word` VALUES ('2436', '379', 'resume', '[ri\'zju:m, -\'zu:m]', null, 'v.（中断后）重新开始', null, null, null);
INSERT INTO `word` VALUES ('2437', '380', 'severe', '[si\'viə]', null, 'a.严重的', null, null, null);
INSERT INTO `word` VALUES ('2438', '381', 'sexual', '[\'seksjuəl, -ʃuəl]', null, 'a.性的', null, null, null);
INSERT INTO `word` VALUES ('2439', '382', 'simplicity', '[sim\'plisiti]', null, 'n.简单；朴素', null, null, null);
INSERT INTO `word` VALUES ('2440', '383', 'simplify', '[\'simplifai]', null, 'vt.简化', null, null, null);
INSERT INTO `word` VALUES ('2441', '384', 'sorrow', '[\'sɔrəu, \'sɔ:-]', null, 'n.悲哀，悲痛', null, null, null);
INSERT INTO `word` VALUES ('2442', '385', 'stuff', '[stʌf]', null, 'n.原料，材料 vt.填进，塞满', null, null, null);
INSERT INTO `word` VALUES ('2443', '386', 'temporary', '[\'tempərəri]', null, 'a.暂时的，临时的', null, null, null);
INSERT INTO `word` VALUES ('2444', '387', 'temptation', '[temp\'teiʃən]', null, 'n.诱惑，引诱', null, null, null);
INSERT INTO `word` VALUES ('2445', '388', 'terror', '[\'terə]', null, 'n.恐怖', null, null, null);
INSERT INTO `word` VALUES ('2446', '389', 'thrust', '[θrʌst]', null, 'v.挤，推，插', null, null, null);
INSERT INTO `word` VALUES ('2447', '390', 'treaty', '[\'tri:ti]', null, 'n.条约，协定', null, null, null);
INSERT INTO `word` VALUES ('2448', '391', 'arise', '[ə\'raiz]', null, 'vi.产生，出现，发生；起身', null, null, null);
INSERT INTO `word` VALUES ('2449', '392', 'arouse', '[ə\'rəuz]', null, 'vt.引起，激起；唤醒', null, null, null);
INSERT INTO `word` VALUES ('2450', '393', 'burden', '[\'bə:dən]', null, 'n.重担，负荷', null, null, null);
INSERT INTO `word` VALUES ('2451', '394', 'bureau', '[\'bjuərəu]', null, 'n.局，办事处', null, null, null);
INSERT INTO `word` VALUES ('2452', '395', 'marvelous', '[\'mɑrvələs]', null, 'a.奇迹般的，惊人的', null, null, null);
INSERT INTO `word` VALUES ('2453', '396', 'massive', '[\'mæsiv]', null, 'a.大的，大量的，大块的', null, null, null);
INSERT INTO `word` VALUES ('2454', '397', 'mature', '[mə\'tjuə]', null, 'a.成熟的', null, null, null);
INSERT INTO `word` VALUES ('2455', '398', 'maximum', '[\'mæksiməm]', null, 'a.最高的，最大的', null, null, null);
INSERT INTO `word` VALUES ('2456', '399', 'minimum', '[\'miniməm]', null, 'a.最低的，最小的', null, null, null);
INSERT INTO `word` VALUES ('2457', '400', 'nonsense', '[\'nɔnsəns]', null, 'n.胡说，冒失的行动', null, null, null);
INSERT INTO `word` VALUES ('2458', '401', 'nuclear', '[\'nju:kliə, \'nu:-]', null, 'a.核子的，核能的', null, null, null);
INSERT INTO `word` VALUES ('2459', '402', 'nucleus', '[\'nju:kliəs]', null, 'n.核', null, null, null);
INSERT INTO `word` VALUES ('2460', '403', 'retail', '[\'ri:teil]', null, 'n./v./ad.零售', null, null, null);
INSERT INTO `word` VALUES ('2461', '404', 'retain', '[ri\'tein]', null, 'vt.保留，保持', null, null, null);
INSERT INTO `word` VALUES ('2462', '405', 'restrict', '[ri\'strikt]', null, 'vt.限制，约束', null, null, null);
INSERT INTO `word` VALUES ('2463', '406', 'sponsor', '[\'spɔnsə]', null, 'n.发起者，主办者 vt.发起，主办，资助', null, null, null);
INSERT INTO `word` VALUES ('2464', '407', 'spur', '[spə:]', null, 'n./vt.刺激，激励', null, null, null);
INSERT INTO `word` VALUES ('2465', '408', 'triumph', '[\'traiəmf, -ʌmf]', null, 'n.胜利，成功', null, null, null);
INSERT INTO `word` VALUES ('2466', '409', 'tuition', '[tju:\'iʃən]', null, 'n.学费', null, null, null);
INSERT INTO `word` VALUES ('2467', '410', 'twist', '[twist]', null, 'vt.使缠绕；转动；扭歪', null, null, null);
INSERT INTO `word` VALUES ('2468', '411', 'undergraduate', '[,ʌndə\'ɡrædjuət]', null, 'n.大学肄业生', null, null, null);
INSERT INTO `word` VALUES ('2469', '412', 'universal', '[,ju:ni\'və:səl]', null, 'a.普遍的，通用的；宇宙的', null, null, null);
INSERT INTO `word` VALUES ('2470', '413', 'universe', '[\'ju:nivə:s]', null, 'n.宇宙', null, null, null);
INSERT INTO `word` VALUES ('2471', '414', 'via', '[\'vaiə]', null, 'prep.经由，经过，通过', null, null, null);
INSERT INTO `word` VALUES ('2472', '415', 'vibrate', '[vai\'breit]', null, 'v.振动，摇摆', null, null, null);
INSERT INTO `word` VALUES ('2473', '416', 'virus', '[\'vaiərəs]', null, 'n.病毒', null, null, null);
INSERT INTO `word` VALUES ('2474', '417', 'voluntary', '[\'vɔləntəri]', null, 'a.自愿的', null, null, null);
INSERT INTO `word` VALUES ('2475', '418', 'volunteer', '[,vɔlən\'tiə]', null, 'n.志愿者 v.自愿（做）', null, null, null);
INSERT INTO `word` VALUES ('2476', '419', 'vote', '[vəut]', null, 'v.选举 n.选票', null, null, null);
INSERT INTO `word` VALUES ('2477', '420', 'wagon', '[\'wæɡən]', null, 'n.四轮马车，铁路货车 ', null, null, null);
INSERT INTO `word` VALUES ('2478', '421', 'appoint', '[ə\'pɔint]', null, 'vt.任命，委派', null, null, null);
INSERT INTO `word` VALUES ('2479', '422', 'approach', '[ə\'prəutʃ]', null, 'v.靠近，接近 n.途径，方式', null, null, null);
INSERT INTO `word` VALUES ('2480', '423', 'appropriate', '[ə\'prəuprieit, ə\'prəupriət]', null, 'a.适当的', null, null, null);
INSERT INTO `word` VALUES ('2481', '424', 'bunch', '[\'bʌntʃ]', null, 'n.群，伙；束，串', null, null, null);
INSERT INTO `word` VALUES ('2482', '425', 'bundle', '[\'bʌndl]', null, 'n.捆，包，束 vt.收集，归拢', null, null, null);
INSERT INTO `word` VALUES ('2483', '426', 'ceremony', '[\'seriməuni]', null, 'n.典礼，仪式', null, null, null);
INSERT INTO `word` VALUES ('2484', '427', 'chaos', '[\'keiɔs]', null, 'n.混乱，紊乱', null, null, null);
INSERT INTO `word` VALUES ('2485', '428', 'discount', '[\'diskaunt, dis\'k-]', null, 'n.（价格）折扣', null, null, null);
INSERT INTO `word` VALUES ('2486', '429', 'display', '[,dis\'plei]', null, 'n./vt.陈列，展览', null, null, null);
INSERT INTO `word` VALUES ('2487', '430', 'equivalent', '[i\'kwivələnt]', null, 'a.相等的 a.相等物', null, null, null);
INSERT INTO `word` VALUES ('2488', '431', 'erect', '[i\'rekt]', null, 'a.竖直的 v.建造，竖立', null, null, null);
INSERT INTO `word` VALUES ('2489', '432', 'fax', '[fæks]', null, 'n./vt.传真', null, null, null);
INSERT INTO `word` VALUES ('2490', '433', 'fertile', '[\'fɜːtaɪl]', null, 'a.肥沃的；多产的', null, null, null);
INSERT INTO `word` VALUES ('2491', '434', 'fertilizer', '[\'fə:tilaizə]', null, 'n.肥料', null, null, null);
INSERT INTO `word` VALUES ('2492', '435', 'grateful', '[\'ɡreitful]', null, 'a.感激的', null, null, null);
INSERT INTO `word` VALUES ('2493', '436', 'gratitude', '[\'ɡrætitju:d]', null, 'n.感激', null, null, null);
INSERT INTO `word` VALUES ('2494', '437', 'horror', '[\'hɔrə]', null, 'n.恐怖', null, null, null);
INSERT INTO `word` VALUES ('2495', '438', 'horrible', '[\'hɔrəbl]', null, 'a.可怕的', null, null, null);
INSERT INTO `word` VALUES ('2496', '439', 'Internet', '[\'intənet]', null, 'n.国际互联网，因特网', null, null, null);
INSERT INTO `word` VALUES ('2497', '440', 'interpret', '[in\'tə:prit]', null, 'v.翻译，解释', null, null, null);
INSERT INTO `word` VALUES ('2498', '441', 'interpretation', '[in,tə:pri\'teiʃən]', null, 'n.解释，说明', null, null, null);
INSERT INTO `word` VALUES ('2499', '442', 'jungle', '[\'dʒʌŋɡl]', null, 'n.丛林，密林', null, null, null);
INSERT INTO `word` VALUES ('2500', '443', 'knot', '[nɔt]', null, 'n.结 vt.把...打成结', null, null, null);
INSERT INTO `word` VALUES ('2501', '444', 'leak', '[li:k]', null, 'v.漏，渗出', null, null, null);
INSERT INTO `word` VALUES ('2502', '445', 'lean', '[li:n]', null, 'vi.倾斜，倚，靠', null, null, null);
INSERT INTO `word` VALUES ('2503', '446', 'leap', '[li:p]', null, 'vi.跳跃', null, null, null);
INSERT INTO `word` VALUES ('2504', '447', 'modify', '[\'mɔdifai]', null, 'vt.修改', null, null, null);
INSERT INTO `word` VALUES ('2505', '448', 'nylon', '[\'nailɔn]', null, 'n.尼龙', null, null, null);
INSERT INTO `word` VALUES ('2506', '449', 'onion', '[\'ʌnjən]', null, 'n.洋葱', null, null, null);
INSERT INTO `word` VALUES ('2507', '450', 'powder', '[\'paudə]', null, 'n.粉末 ', null, null, null);
INSERT INTO `word` VALUES ('2508', '451', 'applicable', '[\'æplikəbl, ə\'plikə-]', null, 'a.可应用的，适当的', null, null, null);
INSERT INTO `word` VALUES ('2509', '452', 'applicant', '[\'æplikənt]', null, 'n.申请人', null, null, null);
INSERT INTO `word` VALUES ('2510', '453', 'breadth', '[bredθ]', null, 'n.宽度', null, null, null);
INSERT INTO `word` VALUES ('2511', '454', 'conservation', '[,kɔnsə\'veiʃən]', null, 'n.保存，保护', null, null, null);
INSERT INTO `word` VALUES ('2512', '455', 'conservative', '[kən\'sə:vətiv]', null, 'a.保守的', null, null, null);
INSERT INTO `word` VALUES ('2513', '456', 'parallel', '[\'pærəlel]', null, 'n.平行线；可相比拟的事物', null, null, null);
INSERT INTO `word` VALUES ('2514', '457', 'passion', '[\'pæʃən]', null, 'n.激情，热情', null, null, null);
INSERT INTO `word` VALUES ('2515', '458', 'passive', '[\'pæsiv]', null, 'a.被动的，消极的', null, null, null);
INSERT INTO `word` VALUES ('2516', '459', 'pat', '[pæt]', null, 'v./n.轻拍，轻打', null, null, null);
INSERT INTO `word` VALUES ('2517', '460', 'peak', '[pi:k]', null, 'n.山峰，顶点', null, null, null);
INSERT INTO `word` VALUES ('2518', '461', 'phenomenon', '[fi\'nɔminən, fə-]', null, 'n.现象', null, null, null);
INSERT INTO `word` VALUES ('2519', '462', 'reluctant', '[ri\'lʌktənt]', null, 'a.不情愿的，勉强的', null, null, null);
INSERT INTO `word` VALUES ('2520', '463', 'rely', '[ri\'lai]', null, 'vi.(on ,upon)依赖，指望', null, null, null);
INSERT INTO `word` VALUES ('2521', '464', 'relevant', '[\'reləvənt]', null, 'a.有关的，切题的', null, null, null);
INSERT INTO `word` VALUES ('2522', '465', 'reliable', '[ri\'laiəbl]', null, 'a.可靠的', null, null, null);
INSERT INTO `word` VALUES ('2523', '466', 'relief', '[ri\'li:f]', null, 'n.轻松，宽慰；减轻', null, null, null);
INSERT INTO `word` VALUES ('2524', '467', 'reputation', '[,repju\'teiʃən]', null, 'n.名气，声誉', null, null, null);
INSERT INTO `word` VALUES ('2525', '468', 'rescue', '[\'reskju:]', null, 'vt./n.营救', null, null, null);
INSERT INTO `word` VALUES ('2526', '469', 'triangle', '[\'traiæŋɡl]', null, 'n.三角（形）', null, null, null);
INSERT INTO `word` VALUES ('2527', '470', 'sequence', '[\'si:kwəns]', null, 'n.连续；顺序', null, null, null);
INSERT INTO `word` VALUES ('2528', '471', 'shallow', '[\'ʃæləu]', null, 'a.浅的', null, null, null);
INSERT INTO `word` VALUES ('2529', '472', 'shiver', '[\'ʃivə]', null, 'vi/n.发抖', null, null, null);
INSERT INTO `word` VALUES ('2530', '473', 'shrug', '[ʃrʌɡ]', null, 'v./n.耸肩', null, null, null);
INSERT INTO `word` VALUES ('2531', '474', 'signature', '[\'signətʃə]', null, 'n.签名', null, null, null);
INSERT INTO `word` VALUES ('2532', '475', 'sincere', '[sin\'siə]', null, 'a.诚挚的，真诚的', null, null, null);
INSERT INTO `word` VALUES ('2533', '476', 'utility', '[juːˈtɪləti]', null, 'n.功用，效用', null, null, null);
INSERT INTO `word` VALUES ('2534', '477', 'utilise', '[\'ju:tilaiz]', null, 'vt.利用', null, null, null);
INSERT INTO `word` VALUES ('2535', '478', 'utter', '[\'ʌtə]', null, 'vt.说出 a.完全的，彻底的', null, null, null);
INSERT INTO `word` VALUES ('2536', '479', 'variation', '[,vεəri\'eiʃən]', null, 'n.变化，变动', null, null, null);
INSERT INTO `word` VALUES ('2537', '480', 'vehicle', '[\'vi:ikl, জɦ׶ॏѧvi:hi-]', null, 'n.交通工具，车辆 ', null, null, null);
INSERT INTO `word` VALUES ('2538', '481', 'applause', '[ə\'plɔ:z]', null, 'n.鼓掌，掌声', null, null, null);
INSERT INTO `word` VALUES ('2539', '482', 'appliance', '[ə\'plaiəns]', null, 'n.器具，器械', null, null, null);
INSERT INTO `word` VALUES ('2540', '483', 'consent', '[kən\'sent]', null, 'n.准许，同意 vi (to)准许，同意', null, null, null);
INSERT INTO `word` VALUES ('2541', '484', 'conquer', '[\'kɔŋkə]', null, 'vt.征服', null, null, null);
INSERT INTO `word` VALUES ('2542', '485', 'defect', '[\'di:fekt, di\'f-, di\'fekt]', null, 'n.缺点，缺陷', null, null, null);
INSERT INTO `word` VALUES ('2543', '486', 'delicate', '[\'delikət]', null, 'a.易碎的；娇弱的；精美的', null, null, null);
INSERT INTO `word` VALUES ('2544', '487', 'evolve', '[i\'vɔlv]', null, 'v.演变', null, null, null);
INSERT INTO `word` VALUES ('2545', '488', 'evolution', '[,i:və\'lu:ʃən, ,ev-]', null, 'n.演变，进化', null, null, null);
INSERT INTO `word` VALUES ('2546', '489', 'frown', '[fraun]', null, 'v./n.皱眉', null, null, null);
INSERT INTO `word` VALUES ('2547', '490', 'frustrate', '[frʌs\'treit]', null, 'vt.使沮丧', null, null, null);
INSERT INTO `word` VALUES ('2548', '491', 'guarantee', '[,ɡærən\'ti:]', null, 'vt./n.保证', null, null, null);
INSERT INTO `word` VALUES ('2549', '492', 'guilty', '[\'ɡilti]', null, 'a.内疚的；有罪的', null, null, null);
INSERT INTO `word` VALUES ('2550', '493', 'jealous', '[\'dʒeləs]', null, 'a.妒忌的', null, null, null);
INSERT INTO `word` VALUES ('2551', '494', 'jeans', '[dʒinz]', null, 'n.牛仔裤', null, null, null);
INSERT INTO `word` VALUES ('2552', '495', 'liquor', '[\'likə]', null, 'n.酒，烈性酒', null, null, null);
INSERT INTO `word` VALUES ('2553', '496', 'liter', '[\'litər]', null, 'n.升', null, null, null);
INSERT INTO `word` VALUES ('2554', '497', 'modest', '[\'mɔdist]', null, 'a.谦虚道', null, null, null);
INSERT INTO `word` VALUES ('2555', '498', 'molecule', '[\'mɔlikjul]', null, 'n.分子', null, null, null);
INSERT INTO `word` VALUES ('2556', '499', 'orbit', '[\'ɔ:bit]', null, 'n.轨道 v.（绕...）作轨道运行', null, null, null);
INSERT INTO `word` VALUES ('2557', '500', 'participate', '[pɑ:\'tisipeit]', null, 'v.(in)参与，参加', null, null, null);
INSERT INTO `word` VALUES ('2558', '501', 'particle', '[\'pɑ:tikl]', null, 'n.微粒', null, null, null);
INSERT INTO `word` VALUES ('2559', '502', 'particularly', '[pə\'tikjuləli]', null, 'ad.特别，尤其', null, null, null);
INSERT INTO `word` VALUES ('2560', '503', 'respond', '[ri\'spɔnd]', null, 'vi.回答，答复；反应', null, null, null);
INSERT INTO `word` VALUES ('2561', '504', 'response', '[ri\'spɔns]', null, 'n.回答，答复；反应', null, null, null);
INSERT INTO `word` VALUES ('2562', '505', 'sensible', '[\'sensəbl]', null, 'a.明智的', null, null, null);
INSERT INTO `word` VALUES ('2563', '506', 'sensitive', '[\'sensitiv]', null, 'a.敏感到，灵敏的', null, null, null);
INSERT INTO `word` VALUES ('2564', '507', 'tremble', '[\'trembl]', null, 'vi.颤抖', null, null, null);
INSERT INTO `word` VALUES ('2565', '508', 'tremendous', '[tri\'mendəs]', null, 'a.巨大的；精彩的', null, null, null);
INSERT INTO `word` VALUES ('2566', '509', 'trend', '[trend]', null, 'n.趋向，倾向', null, null, null);
INSERT INTO `word` VALUES ('2567', '510', 'trial', '[\'traiəl]', null, 'n.审讯；试验 ', null, null, null);
INSERT INTO `word` VALUES ('2568', '511', 'apparent', '[ə\'pærənt]', null, 'a.显然的，明白的', null, null, null);
INSERT INTO `word` VALUES ('2569', '512', 'appetite', '[\'æpitait]', null, 'n.胃口；欲望', null, null, null);
INSERT INTO `word` VALUES ('2570', '513', 'deposit', '[di\'pɔzit]', null, 'n.存款，定金 v.存放，储蓄', null, null, null);
INSERT INTO `word` VALUES ('2571', '514', 'deputy', '[\'depjuti]', null, 'n.副职，代表', null, null, null);
INSERT INTO `word` VALUES ('2572', '515', 'derive', '[di\'raiv]', null, 'vt.取得，得到；(from)起源于', null, null, null);
INSERT INTO `word` VALUES ('2573', '516', 'descend', '[di\'send]', null, 'v.下来，下降', null, null, null);
INSERT INTO `word` VALUES ('2574', '517', 'missile', '[\'misail, -səl]', null, 'n.导弹', null, null, null);
INSERT INTO `word` VALUES ('2575', '518', 'mission', '[\'miʃən]', null, 'n.使命；代表团', null, null, null);
INSERT INTO `word` VALUES ('2576', '519', 'mist', '[mist]', null, 'n.薄雾', null, null, null);
INSERT INTO `word` VALUES ('2577', '520', 'noticeable', '[\'nəutisəbl]', null, 'a.显而易见到', null, null, null);
INSERT INTO `word` VALUES ('2578', '521', 'notify', '[\'nəutifai]', null, 'vt.通知，告知', null, null, null);
INSERT INTO `word` VALUES ('2579', '522', 'notion', '[\'nəuʃən]', null, 'n.概念；意图，想法', null, null, null);
INSERT INTO `word` VALUES ('2580', '523', 'resemble', '[ri\'zembl]', null, 'vt.像，类似于', null, null, null);
INSERT INTO `word` VALUES ('2581', '524', 'reveal', '[ri\'vi:l]', null, 'vt.揭露', null, null, null);
INSERT INTO `word` VALUES ('2582', '525', 'revenue', '[\'revənju:, -nu:]', null, 'n.收入，岁入；税收', null, null, null);
INSERT INTO `word` VALUES ('2583', '526', 'shelter', '[\'ʃeltə]', null, 'n.掩蔽处；住所', null, null, null);
INSERT INTO `word` VALUES ('2584', '527', 'shield', '[ʃi:ld]', null, 'n.防护物，盾 vt.保护，防护', null, null, null);
INSERT INTO `word` VALUES ('2585', '528', 'vital', '[\'vaitəl]', null, 'a.重要的；致命的，生命的', null, null, null);
INSERT INTO `word` VALUES ('2586', '529', 'vitally', '[\'vaɪtəli]', null, 'ad.极度，非常；致命地', null, null, null);
INSERT INTO `word` VALUES ('2587', '530', 'urban', '[\'ə:bən]', null, 'a.城市的', null, null, null);
INSERT INTO `word` VALUES ('2588', '531', 'urge', '[ə:dʒ]', null, 'vt.鼓励，激励', null, null, null);
INSERT INTO `word` VALUES ('2589', '532', 'urgent', '[\'ə:dʒənt]', null, 'a.急迫的，紧急得', null, null, null);
INSERT INTO `word` VALUES ('2590', '533', 'usage', '[\'ju:zidʒ]', null, 'n.使用，用法', null, null, null);
INSERT INTO `word` VALUES ('2591', '534', 'violence', '[\'vaiələns]', null, 'n.强力，暴力', null, null, null);
INSERT INTO `word` VALUES ('2592', '535', 'violent', '[\'vaiələnt]', null, 'a.强暴的', null, null, null);
INSERT INTO `word` VALUES ('2593', '536', 'violet', '[\'vaiələt]', null, 'a.紫色的', null, null, null);
INSERT INTO `word` VALUES ('2594', '537', 'weed', '[wi:d]', null, 'n.杂草，野草', null, null, null);
INSERT INTO `word` VALUES ('2595', '538', 'welfare', '[\'welfεə]', null, 'n.福利', null, null, null);
INSERT INTO `word` VALUES ('2596', '539', 'whatsoever', '[wɒtsəʊ\'evə]', null, 'ad.（用于否定句）任何', null, null, null);
INSERT INTO `word` VALUES ('2597', '540', 'whereas', '[hwεə\'æz]', null, 'conj.然而，但是，尽管', null, null, null);
INSERT INTO `word` VALUES ('2598', '541', 'essential', '[i\'senʃəl]', null, 'a.必不可少的；本质的', null, null, null);
INSERT INTO `word` VALUES ('2599', '542', 'estimate', '[\'estimeit]', null, 'n./vt.估计，估量', null, null, null);
INSERT INTO `word` VALUES ('2600', '543', 'evaluate', '[i\'væljueit]', null, 'vt.评估，评价', null, null, null);
INSERT INTO `word` VALUES ('2601', '544', 'exceed', '[ik\'si:d]', null, 'vt.超过，越出', null, null, null);
INSERT INTO `word` VALUES ('2602', '545', 'exceedingly', '[ik\'si:diŋli]', null, 'ad.非常，极其', null, null, null);
INSERT INTO `word` VALUES ('2603', '546', 'exclaim', '[ik\'skleim]', null, 'v.呼喊，大声说', null, null, null);
INSERT INTO `word` VALUES ('2604', '547', 'exclude', '[iks\'klu:d]', null, 'vt.把...排斥在外，不包括', null, null, null);
INSERT INTO `word` VALUES ('2605', '548', 'exclusive', '[ik\'sklu:siv]', null, 'a.读有的，排他的', null, null, null);
INSERT INTO `word` VALUES ('2606', '549', 'excursion', '[ik\'skə:ʃən]', null, 'n.远足', null, null, null);
INSERT INTO `word` VALUES ('2607', '550', 'flash', '[flæʃ]', null, 'vi.闪光，闪耀', null, null, null);
INSERT INTO `word` VALUES ('2608', '551', 'flee', '[fli:]', null, 'vi.逃走', null, null, null);
INSERT INTO `word` VALUES ('2609', '552', 'flexible', '[\'fleksibl]', null, 'a.易弯曲的', null, null, null);
INSERT INTO `word` VALUES ('2610', '553', 'flock', '[flɔk]', null, 'n.羊群，（鸟兽等）一群；一伙人', null, null, null);
INSERT INTO `word` VALUES ('2611', '554', 'hardware', '[\'hɑ:dwεə]', null, 'n.五金器具', null, null, null);
INSERT INTO `word` VALUES ('2612', '555', 'harmony', '[\'hɑ:məni]', null, 'n.和谐，融洽', null, null, null);
INSERT INTO `word` VALUES ('2613', '556', 'haste', '[heist]', null, 'n.急速，急忙', null, null, null);
INSERT INTO `word` VALUES ('2614', '557', 'hatred', '[\'heitrid]', null, 'n.憎恶，憎恨', null, null, null);
INSERT INTO `word` VALUES ('2615', '558', 'incident', '[\'insidənt]', null, 'n.事件，事变', null, null, null);
INSERT INTO `word` VALUES ('2616', '559', 'index', '[\'indeks]', null, 'n.索引，标志', null, null, null);
INSERT INTO `word` VALUES ('2617', '560', 'infant', '[\'infənt]', null, 'n.婴儿', null, null, null);
INSERT INTO `word` VALUES ('2618', '561', 'infect', '[in\'fekt]', null, 'v.传染', null, null, null);
INSERT INTO `word` VALUES ('2619', '562', 'inferior', '[in\'fiəriə]', null, 'a.劣等的，次的，下级的', null, null, null);
INSERT INTO `word` VALUES ('2620', '563', 'infinite', '[\'infinət]', null, 'a.无限的', null, null, null);
INSERT INTO `word` VALUES ('2621', '564', 'ingredient', '[in\'ɡri:diənt]', null, 'n.组成部分', null, null, null);
INSERT INTO `word` VALUES ('2622', '565', 'inhabitant', '[in\'hæbitənt]', null, 'n.居民', null, null, null);
INSERT INTO `word` VALUES ('2623', '566', 'jail', '[dʒeil]', null, 'n.监狱', null, null, null);
INSERT INTO `word` VALUES ('2624', '567', 'jam', '[dʒæm]', null, 'n.果酱；拥挤，堵塞', null, null, null);
INSERT INTO `word` VALUES ('2625', '568', 'jewel', '[\'dʒu:əl]', null, 'n.宝石', null, null, null);
INSERT INTO `word` VALUES ('2626', '569', 'joint', '[dʒɔint]', null, 'a.连接的；共同的', null, null, null);
INSERT INTO `word` VALUES ('2627', '570', 'junior', '[\'dʒu:njə]', null, 'a.年少的；资历较浅的 ', null, null, null);
INSERT INTO `word` VALUES ('2628', '571', 'laser', '[\'leizə]', null, 'n.激光', null, null, null);
INSERT INTO `word` VALUES ('2629', '572', 'launch', '[lɔ:ntʃ, lɑ:ntʃ]', null, 'vt.发动，发起', null, null, null);
INSERT INTO `word` VALUES ('2630', '573', 'luxury', '[\'lʌkʃəri, \'lʌɡʒəri]', null, 'n.奢侈；奢侈品', null, null, null);
INSERT INTO `word` VALUES ('2631', '574', 'magnet', '[\'mæɡnit]', null, 'n.磁铁，磁体', null, null, null);
INSERT INTO `word` VALUES ('2632', '575', 'male', '[meil]', null, 'a.男性的，雄的', null, null, null);
INSERT INTO `word` VALUES ('2633', '576', 'female', '[\'fi:meil]', null, 'a.女性的，雌的', null, null, null);
INSERT INTO `word` VALUES ('2634', '577', 'manual', '[\'mænjuəl]', null, 'a.用手的，手工做的 n.手册', null, null, null);
INSERT INTO `word` VALUES ('2635', '578', 'manufacture', '[,mænju\'fæktʃə]', null, 'vt./n.制造，加工', null, null, null);
INSERT INTO `word` VALUES ('2636', '579', 'marine', '[mə\'ri:n]', null, 'a.海的；海产的', null, null, null);
INSERT INTO `word` VALUES ('2637', '580', 'mutual', '[\'mju:tʃuəl, -tjuəl]', null, 'a.相互的', null, null, null);
INSERT INTO `word` VALUES ('2638', '581', 'naked', '[\'neikid]', null, 'a.裸露的', null, null, null);
INSERT INTO `word` VALUES ('2639', '582', 'negative', '[\'neɡətiv]', null, 'a.否定的，消极的', null, null, null);
INSERT INTO `word` VALUES ('2640', '583', 'neglect', '[ni\'ɡlekt]', null, 'vt.忽视，忽略', null, null, null);
INSERT INTO `word` VALUES ('2641', '584', 'origin', '[\'ɔridʒin, \'ɔ:-]', null, 'n.起源，出身', null, null, null);
INSERT INTO `word` VALUES ('2642', '585', 'oval', '[\'əuvəl]', null, 'a.椭圆形的 n.椭圆形', null, null, null);
INSERT INTO `word` VALUES ('2643', '586', 'outset', '[\'autset]', null, 'n.开始，开端', null, null, null);
INSERT INTO `word` VALUES ('2644', '587', 'presumably', '[pri\'zju:-məbli,pri:-]', null, 'ad.大概，可能', null, null, null);
INSERT INTO `word` VALUES ('2645', '588', 'prevail', '[pri\'veil, pri:-]', null, 'vi.流行，盛行', null, null, null);
INSERT INTO `word` VALUES ('2646', '589', 'quit', '[kwit]', null, 'v.停止', null, null, null);
INSERT INTO `word` VALUES ('2647', '590', 'quotation', '[kwəu\'teiʃən, kəu-]', null, 'n.引文，引语', null, null, null);
INSERT INTO `word` VALUES ('2648', '591', 'recreation', '[,rekri\'eiʃən, -kri:-]', null, 'n.娱乐活动', null, null, null);
INSERT INTO `word` VALUES ('2649', '592', 'recruit', '[ri\'kru:t]', null, 'vt.招募，吸收（新成员）', null, null, null);
INSERT INTO `word` VALUES ('2650', '593', 'rival', '[\'raivəl]', null, 'n.竞争对手，敌手', null, null, null);
INSERT INTO `word` VALUES ('2651', '594', 'shuttle', '[\'ʃʌtl]', null, 'n.梭子；航天飞机', null, null, null);
INSERT INTO `word` VALUES ('2652', '595', 'skim', '[skim]', null, 'vt.搬（去），掠过；浏览', null, null, null);
INSERT INTO `word` VALUES ('2653', '596', 'sketch', '[sketʃ]', null, 'n.草图；梗概', null, null, null);
INSERT INTO `word` VALUES ('2654', '597', 'slender', '[\'slendə]', null, 'a.苗条的，修长的', null, null, null);
INSERT INTO `word` VALUES ('2655', '598', 'theme', '[θi:m]', null, 'n.主题', null, null, null);
INSERT INTO `word` VALUES ('2656', '599', 'textile', '[\'tekstail, -til]', null, 'n.纺织品', null, null, null);
INSERT INTO `word` VALUES ('2657', '600', 'tropical', '[\'trɔpikəl]', null, 'a.热带的，炎热的', null, null, null);
INSERT INTO `word` VALUES ('2658', '601', 'kneel', '[ni:l]', null, 'vi.跪', null, null, null);
INSERT INTO `word` VALUES ('2659', '602', 'label', '[\'leibl]', null, 'n.标签', null, null, null);
INSERT INTO `word` VALUES ('2660', '603', 'merchant', '[\'mə:tʃənt]', null, 'n.商人', null, null, null);
INSERT INTO `word` VALUES ('2661', '604', 'mere', '[miə]', null, 'a.仅仅的，只不过的；纯粹的', null, null, null);
INSERT INTO `word` VALUES ('2662', '605', 'nuisance', '[\'nju:səns]', null, 'n.令人讨厌的东西（或人）', null, null, null);
INSERT INTO `word` VALUES ('2663', '606', 'numerous', '[\'njuːm(ə)rəs]', null, 'a.众多的，许多的', null, null, null);
INSERT INTO `word` VALUES ('2664', '607', 'parade', '[pə\'reid]', null, 'n.游行 v.列队行进', null, null, null);
INSERT INTO `word` VALUES ('2665', '608', 'pants', '[pænts]', null, 'n.长裤；内裤', null, null, null);
INSERT INTO `word` VALUES ('2666', '609', 'partial', '[\'pɑ:ʃəl]', null, 'a.部分的', null, null, null);
INSERT INTO `word` VALUES ('2667', '610', 'passport', '[\'pɑ:spɔ:t, \'pæs-]', null, 'n.护照', null, null, null);
INSERT INTO `word` VALUES ('2668', '611', 'prescribe', '[pris\'kraib]', null, 'vt.开药，吩咐采用...疗法', null, null, null);
INSERT INTO `word` VALUES ('2669', '612', 'primitive', '[\'primitiv]', null, 'a.原始的，早期的', null, null, null);
INSERT INTO `word` VALUES ('2670', '613', 'ridge', '[ridʒ]', null, 'n.脊，山脊，埂', null, null, null);
INSERT INTO `word` VALUES ('2671', '614', 'ridiculous', '[ri\'dikjuləs]', null, 'a.可笑的，荒漠的', null, null, null);
INSERT INTO `word` VALUES ('2672', '615', 'rigid', '[\'rɪdʒɪd]', null, 'a.严格的；僵硬的', null, null, null);
INSERT INTO `word` VALUES ('2673', '616', 'withstand', '[wið\'stænd, wiθ-]', null, 'vt.经受，承受', null, null, null);
INSERT INTO `word` VALUES ('2674', '617', 'witness', '[\'witnis]', null, 'n.目击者；证据 vt.注意到；证明', null, null, null);
INSERT INTO `word` VALUES ('2675', '618', 'withdraw', '[wið\'drɔ:, wiθ-]', null, 'v.收回，撤销', null, null, null);
INSERT INTO `word` VALUES ('2676', '619', 'slippery', '[\'slipəri]', null, 'a.滑的', null, null, null);
INSERT INTO `word` VALUES ('2677', '620', 'smash', '[smæʃ]', null, 'vt.粉碎，打烂', null, null, null);
INSERT INTO `word` VALUES ('2678', '621', 'snap', '[snæp]', null, 'n./vt.折断，拉断；快照', null, null, null);
INSERT INTO `word` VALUES ('2679', '622', 'software', '[\'sɔftwεə, \'sɔ:-]', null, 'n.软件', null, null, null);
INSERT INTO `word` VALUES ('2680', '623', 'solar', '[\'səulə]', null, 'a.太阳的', null, null, null);
INSERT INTO `word` VALUES ('2681', '624', 'lunar', '[\'luːnə]', null, 'a.月的，月球的', null, null, null);
INSERT INTO `word` VALUES ('2682', '625', 'submerge', '[səb\'mə:dʒ]', null, 'vi.潜入水中', null, null, null);
INSERT INTO `word` VALUES ('2683', '626', 'submit', '[səb\'mit]', null, 'vi.(to)屈服，听从', null, null, null);
INSERT INTO `word` VALUES ('2684', '627', 'timber', '[\'timbə]', null, 'n.木材，原木', null, null, null);
INSERT INTO `word` VALUES ('2685', '628', 'tissue', '[\'tiʃju:, -sju:]', null, 'n.组织；薄纱，手巾纸', null, null, null);
INSERT INTO `word` VALUES ('2686', '629', 'title', '[\'taitl]', null, 'n.题目，标题', null, null, null);
INSERT INTO `word` VALUES ('2687', '630', 'tone', '[təun]', null, 'n.语气，音调631.drift vi.漂，漂流', null, null, null);
INSERT INTO `word` VALUES ('2688', '632', 'drip', '[drip]', null, 'n.滴', null, null, null);
INSERT INTO `word` VALUES ('2689', '633', 'durable', '[\'djuərəbl]', null, 'a.耐用的，持久的', null, null, null);
INSERT INTO `word` VALUES ('2690', '634', 'duration', '[djuə\'reiʃən]', null, 'n.持续，持续期间', null, null, null);
INSERT INTO `word` VALUES ('2691', '635', 'dusk', '[dʌsk]', null, 'n.黄昏，薄暮', null, null, null);
INSERT INTO `word` VALUES ('2692', '636', 'leather', '[\'leðə]', null, 'n.皮革', null, null, null);
INSERT INTO `word` VALUES ('2693', '637', 'legislation', '[,ledʒis\'leiʃən]', null, 'n.法律，法规；立法', null, null, null);
INSERT INTO `word` VALUES ('2694', '638', 'leisure', '[\'leʒə]', null, 'n.闲暇；悠闲', null, null, null);
INSERT INTO `word` VALUES ('2695', '639', 'loose', '[lu:s]', null, 'a.松的，宽松的', null, null, null);
INSERT INTO `word` VALUES ('2696', '640', 'loosen', '[\'lu:sən]', null, 'v.解开，放松', null, null, null);
INSERT INTO `word` VALUES ('2697', '641', 'tarnest', '[tɑːn]', null, 'a.认真的，诚挚的', null, null, null);
INSERT INTO `word` VALUES ('2698', '642', 'earthquake', '[\'ə:θkweik]', null, 'n.地震', null, null, null);
INSERT INTO `word` VALUES ('2699', '643', 'echo', '[\'ekəu]', null, 'n.回音，回声', null, null, null);
INSERT INTO `word` VALUES ('2700', '644', 'elaborate', '[i\'læbərət, i\'læbəreit]', null, 'a.精心设计的，复杂的', null, null, null);
INSERT INTO `word` VALUES ('2701', '645', 'elastic', '[i\'læstik]', null, 'n.橡皮圈（带） a.有弹性的', null, null, null);
INSERT INTO `word` VALUES ('2702', '646', 'elbow', '[\'elbəu]', null, 'n.肘', null, null, null);
INSERT INTO `word` VALUES ('2703', '647', 'electron', '[i\'lektrɔn]', null, 'n.电子', null, null, null);
INSERT INTO `word` VALUES ('2704', '648', 'volcano', '[vɔl\'keinəu]', null, 'n.火山', null, null, null);
INSERT INTO `word` VALUES ('2705', '649', 'volume', '[\'vɔlju:m]', null, 'n.卷，册；体积，容量', null, null, null);
INSERT INTO `word` VALUES ('2706', '650', 'fatigue', '[fə\'ti:ɡ]', null, 'n.疲劳，劳累', null, null, null);
INSERT INTO `word` VALUES ('2707', '651', 'faulty', '[\'fɔ:lti]', null, 'a.有错误的，有缺点的', null, null, null);
INSERT INTO `word` VALUES ('2708', '652', 'favorable', '[\'feivərəbl]', null, 'a.称赞道；有利的，顺利的', null, null, null);
INSERT INTO `word` VALUES ('2709', '653', 'favorite', '[\'feivərit]', null, 'a.特别受喜欢的 n.喜爱的人或物', null, null, null);
INSERT INTO `word` VALUES ('2710', '654', 'gallery', '[\'ɡæləri]', null, 'n.画廊', null, null, null);
INSERT INTO `word` VALUES ('2711', '655', 'gallon', '[\'ɡælən]', null, 'n.加仑', null, null, null);
INSERT INTO `word` VALUES ('2712', '656', 'gap', '[ɡæp]', null, 'n.间隔，差距', null, null, null);
INSERT INTO `word` VALUES ('2713', '657', 'garbage', '[\'ɡɑ:bidʒ]', null, 'n.垃圾，废物', null, null, null);
INSERT INTO `word` VALUES ('2714', '658', 'gaze', '[ɡeiz]', null, 'v.凝视，注视', null, null, null);
INSERT INTO `word` VALUES ('2715', '659', 'gear', '[ɡiə]', null, 'n.齿轮，传动装置', null, null, null);
INSERT INTO `word` VALUES ('2716', '660', 'gene', '[dʒi:n]', null, 'n.基因661.lest conj.唯恐，免得', null, null, null);
INSERT INTO `word` VALUES ('2717', '662', 'liable', '[\'laiəbl]', null, 'a.可能的，大概的； (to)易于...的', null, null, null);
INSERT INTO `word` VALUES ('2718', '663', 'liberal', '[\'libərəl]', null, 'a.自由得', null, null, null);
INSERT INTO `word` VALUES ('2719', '664', 'liberty', '[\'libəti]', null, 'n.自由', null, null, null);
INSERT INTO `word` VALUES ('2720', '665', 'licence', '[\'laisəns]', null, 'n.许可证，执照', null, null, null);
INSERT INTO `word` VALUES ('2721', '666', 'moisture', '[\'mɔistʃə]', null, 'n.潮湿 ', null, null, null);
INSERT INTO `word` VALUES ('2722', '667', 'motivate', '[\'məutiveit]', null, 'vt.激励，激发', null, null, null);
INSERT INTO `word` VALUES ('2723', '668', 'motive', '[\'məutiv]', null, 'n.动机，目的', null, null, null);
INSERT INTO `word` VALUES ('2724', '669', 'generate', '[\'dʒenəreit]', null, 'vt.生成，产生（光、热、电等）', null, null, null);
INSERT INTO `word` VALUES ('2725', '670', 'genius', '[\'dʒi:njəs]', null, 'n.天才，天赋', null, null, null);
INSERT INTO `word` VALUES ('2726', '671', 'genuine', '[\'dʒenjuin]', null, 'a.真的，真诚的', null, null, null);
INSERT INTO `word` VALUES ('2727', '672', 'gasoline', '[\'ɡæsəli:n]', null, 'n.汽油', null, null, null);
INSERT INTO `word` VALUES ('2728', '673', 'germ', '[dʒə:m]', null, 'n.微生物，细菌', null, null, null);
INSERT INTO `word` VALUES ('2729', '674', 'gesture', '[\'dʒestʃə]', null, 'n.姿势，手势', null, null, null);
INSERT INTO `word` VALUES ('2730', '675', 'giant', '[\'dʒaiənt]', null, 'a.巨大的 n.巨人，巨物', null, null, null);
INSERT INTO `word` VALUES ('2731', '676', 'glimpse', '[ɡlimps]', null, 'n.一瞥，一看', null, null, null);
INSERT INTO `word` VALUES ('2732', '677', 'glory', '[\'ɡlɔ:ri]', null, 'n.光荣，荣誉', null, null, null);
INSERT INTO `word` VALUES ('2733', '678', 'glorious', '[\'ɡlɔ:riəs]', null, 'n.光荣的，极好的', null, null, null);
INSERT INTO `word` VALUES ('2734', '679', 'golf', '[ɡɔlf]', null, 'n.高尔夫球运动', null, null, null);
INSERT INTO `word` VALUES ('2735', '680', 'hydrogen', '[\'haidrədʒən]', null, 'n.氢', null, null, null);
INSERT INTO `word` VALUES ('2736', '681', 'oxygen', '[\'ɔksidʒən]', null, 'n.氧', null, null, null);
INSERT INTO `word` VALUES ('2737', '682', 'hostile', '[\'hɔstail, -təl]', null, 'a.敌对的，敌意大', null, null, null);
INSERT INTO `word` VALUES ('2738', '683', 'household', '[\'haushəuld]', null, 'n.家庭，户', null, null, null);
INSERT INTO `word` VALUES ('2739', '684', 'hook', '[huk]', null, 'n.钩', null, null, null);
INSERT INTO `word` VALUES ('2740', '685', 'holy', '[[\'həuli]]', null, 'a.神圣地，圣洁的', null, null, null);
INSERT INTO `word` VALUES ('2741', '686', 'hint', '[hint]', null, 'n.暗示，示意', null, null, null);
INSERT INTO `word` VALUES ('2742', '687', 'hesitate', '[\'hezɪteɪt]', null, 'v.犹豫', null, null, null);
INSERT INTO `word` VALUES ('2743', '688', 'highlight', '[\'hailait]', null, 'vt.强调，突出', null, null, null);
INSERT INTO `word` VALUES ('2744', '689', 'hence', '[hens]', null, 'ad.因此，所以；今后，从此', null, null, null);
INSERT INTO `word` VALUES ('2745', '690', 'herd', '[hɜːd]', null, 'n.兽群，牧群', null, null, null);
